/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app.jframes;
import app.Classes.ClassCrearPaciente;
/**
 *
 * @author Eudy
 */
import conection.Mysql;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class JFrameCrearPacienteSiNoExiste extends javax.swing.JFrame {

    
    private int lineas = 10;
    private String palabraBuscar="",id="";
    private conection.Mysql mysql;
    private ClassCrearPaciente user ;
    private String usuarioID,nombreUsuario,nombreTituloUsuario;
    private String[] datosPaiente;
    private JFrameSelectVistaBuscadorPaciente padre;

    /**
     * Creates new form User
     */
    public JFrameCrearPacienteSiNoExiste() {
        initComponents();
       //this.user.mostrarDatosTabla(jTable1,this.jLabel6);
      // this.jtable();
    }
    public JFrameCrearPacienteSiNoExiste(conection.Mysql mysql) {
       initComponents();
        this.mysql = mysql;
        user = new ClassCrearPaciente(this.mysql); 
        this.user.llenarComboBox(this.jComboBoxSangre);
        //this.user.mostrarDatosTabla(jTable1,this.jLabel6);
       
      // this.jtable();
    }
    public void setPadre(JFrameSelectVistaBuscadorPaciente padre){
        this.padre = padre;
    }
    public void setDatosUsuario(String usuarioID, String nombreUsuario,String nombreTituloUsuario){
        this.usuarioID = usuarioID;
        this.nombreUsuario = nombreUsuario;
        this.nombreTituloUsuario = nombreTituloUsuario;
        JOptionPane.showMessageDialog(null, "Usuario "+this.usuarioID+" "+this.nombreUsuario+" "+this.nombreTituloUsuario);
        this.user.setDatosUsuario(usuarioID, nombreUsuario, nombreTituloUsuario);
    }
    
    /*EJEMPLO SIMPLE PARA MOSTRAR DATOS EN UNA TABLA
    public void jtable(){
            JOptionPane.showMessageDialog(null, "Tabla");
           //DefaultTableModel modelo = (DefaultTableModel) this.jTable1.getModel();
           
           String[] titulos = {"id","usuario"};
           this.lineas = this.lineas + 2;
          //modelo.setColumnIdentifiers(titulos);
           
           Object[][] fila = new Object[this.lineas][2];
           for(int c = 0 ; c < this.lineas ; c++){
               System.out.println("---- x "+ c);
                //for(int i = 0 ; i < 2 ; i++){
                    fila[c][0] = "x "+ c+" y ";
                    //System.out.println("x "+ c+" y "+i);
                    fila[c][1]  = "Eudy";
                    //modelo.addRow(fila);
                //}
           }
          DefaultTableModel modelo = new DefaultTableModel(fila,titulos);
          this.jTable1.setModel(modelo);
    }*/
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldCedula = new javax.swing.JTextField();
        jTextFieldApellido = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jComboBoxSexo = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jComboBoxSangre = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jDateChooserFechaNacimiento = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Administrar Paciente");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Crear Paciente");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("Nombre*");

        jTextFieldNombre.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextFieldNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldNombreFocusLost(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton1.setText("Agregar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel8.setText("Cedula");

        jTextFieldCedula.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextFieldCedula.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldCedulaFocusLost(evt);
            }
        });

        jTextFieldApellido.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextFieldApellido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldApellidoFocusLost(evt);
            }
        });
        jTextFieldApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldApellidoActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel11.setText("Apelllido");

        jComboBoxSexo.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jComboBoxSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MASCULINO", "FEMENINO" }));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel15.setText("Tipo de sangre");

        jComboBoxSangre.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jComboBoxSangre.setToolTipText("");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel18.setText("Fecha Nacimiento");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel19.setText("Sexo");

        jDateChooserFechaNacimiento.setDateFormatString("yyyy-MM-dd");
        jDateChooserFechaNacimiento.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jDateChooserFechaNacimiento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jDateChooserFechaNacimientoFocusLost(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jComboBoxSangre, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldCedula, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextFieldApellido)
                                    .addComponent(jComboBoxSexo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jDateChooserFechaNacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBoxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel19))
                        .addGap(32, 32, 32)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboBoxSangre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooserFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
      // this.jtable();
            String fecha_nacimiento = ((javax.swing.JTextField)this.jDateChooserFechaNacimiento.getDateEditor().getUiComponent()).getText();
      //JOptionPane.showMessageDialog(null, fecha_nacimiento);
      String nombre  = this.jTextFieldNombre.getText();
      String  apellido = this.jTextFieldApellido.getText();
      //String telefonoCasa = this.jTextFieldTelefonoCasa.getText();
      //String telefonoCelular =this.jTextFieldTelefonoCelular.getText();
      //String telefonoTrabajo=this.jTextFieldTelefonoTrabajo.getText();
      //String email1 =this.jTextFieldEmail1.getText();
      String cedula =this.jTextFieldCedula.getText();

      //String email2 =this.jTextFieldEmail2.getText();
      String sexo = this.jComboBoxSexo.getSelectedItem().toString();
      String tipo_sangre = this.user.getIdTipoSangre(this.jComboBoxSangre.getSelectedIndex());
      //String provincia = this.jTextFieldProvincia.getText();
      //String sector = this.jTextFieldSector.getText();
      //String direccion = this.jTextFieldDireccion.getText();
      //String nombreSeguro = this.jTextFieldNombreSeguro.getText();
      //String numeroSeguro = this.jTextFieldNumeroSeguro.getText();
      
       //this.user.setValoresAtributos(nombre, apellido,telefonoCasa,telefonoCelular,telefonoTrabajo,email1,email2,cedula,fecha_nacimiento,sexo,tipo_sangre,provincia,sector,direccion,nombreSeguro,numeroSeguro);                                         

      if(this.user.getAgregar()){
        
      
        //this.user.setValoresAtributos(this.jTextFieldNombre.getText(), this.jTextFieldApellido.getText(),this.jTextFieldTelefonoCasa.getText(),this.jTextFieldTelefonoCelular.getText(),this.jTextFieldTelefonoTrabajo.getText(),this.jTextFieldEmail1.getText(),this.jTextFieldCedula.getText(),this.jTextFieldFechaNacimiento.getText(),this.jComboBoxSexo.getSelectedItem().toString(),tipo_sangre,this.jTextFieldProvincia.getText(),this.jTextFieldSector.getText(),this.jTextFieldDireccion.getText(),this.jTextFieldNombreSeguro.getText(),this.jTextFieldNumeroSeguro.getText());
       //setValoresAtributos(String nombre,String apellido,String telefonoCasa,String telefonoCelular,String telefonoTrabajo,String email1,String email2,String cedula,String fecha_nacimiento,String sexo,String tipo_sangre_id,String provincia,String sector,String direccion,String nombreSeguro,String numeroSeguro); 
       String respuesta = this.user.procesarInsertPaciente(nombre,apellido,cedula,sexo ,/*tipo_sangre_id*/tipo_sangre,fecha_nacimiento);
       
        if( (!respuesta.isEmpty() ) && (!respuesta.equals("0")) ){
            this.datosPaiente = new String[7];
            this.datosPaiente[0] = nombre;
            this.datosPaiente[1] = apellido;
            this.datosPaiente[2] = cedula;
            this.datosPaiente[3] = sexo;
            this.datosPaiente[4] = tipo_sangre;
            this.datosPaiente[5] = fecha_nacimiento;
            this.datosPaiente[6] = respuesta;

            this.padre.setDatosPaciente(datosPaiente);
           // this.user.mostrarDatosTabla(this.jTable1, this.jLabel6);
            //this.user.mostrarNuevoDatoTabla(this.jTable1, this.jLabel6);
            this.user.limpiarTexto(this.jTextFieldNombre, this.jTextFieldApellido,this.jTextFieldApellido,this.jTextFieldApellido,this.jTextFieldCedula,this.jTextFieldApellido,this.jTextFieldApellido,this.jTextFieldApellido,this.jTextFieldApellido,this.jComboBoxSexo,this.jComboBoxSangre,this.jTextFieldApellido,this.jTextFieldApellido,this.jDateChooserFechaNacimiento,this.jTextFieldApellido,this.jTextFieldApellido);
            this.dispose();
        }
      }else{
            //JOptionPane.showMessageDialog(null, type_user);
            //String tipo_sangre = this.user.getIdTipoSangre(this.jComboBoxSangre.getSelectedIndex());
            //this.user.setValoresAtributos(this.jTextFieldNombre.getText(), this.jTextFieldApellido.getText(),this.jTextFieldTelefonoCasa.getText(),this.jTextFieldTelefonoCelular.getText(),this.jTextFieldTelefonoTrabajo.getText(),this.jTextFieldEmail1.getText(),this.jTextFieldCedula.getText(),this.jTextFieldFechaNacimiento.getText(),this.jComboBoxSexo.getSelectedItem().toString(),tipo_sangre,this.jTextFieldProvincia.getText(),this.jTextFieldSector.getText(),this.jTextFieldDireccion.getText(),this.jTextFieldNombreSeguro.getText(),this.jTextFieldNumeroSeguro.getText());
            // this.user.setValoresAtributos(nombre, apellido,telefonoCasa,telefonoCelular,telefonoTrabajo,email1,email2,cedula,fecha_nacimiento,sexo,tipo_sangre,provincia,sector,direccion,nombreSeguro,numeroSeguro,this.id);
      
            //boolean respuesta = this.user.update();
            //if(respuesta){
                //this.user.mostrarDatosTabla(this.jTable1, this.jLabel6);
              //  this.user.setAgregar(true);
               // this.user.cambiarTestoParaEditar(this.jButton1, this.jLabel9,this.jTextFieldNombre);
                //this.user.limpiarTexto(this.jTextFieldNombre, this.jTextFieldApellido,this.jTextFieldTelefonoCelular,this.jTextFieldEmail2,this.jTextFieldCedula,this.jTextFieldTelefonoCasa,this.jTextFieldProvincia,this.jTextFieldSector,this.jTextFieldDireccion,this.jComboBoxSexo,this.jComboBoxSangre,this.jTextFieldNombreSeguro,this.jTextFieldNumeroSeguro,this.jDateChooserFechaNacimiento,this.jTextFieldTelefonoTrabajo,this.jTextFieldEmail1);
            //}
          
      }

    }//GEN-LAST:event_jButton1MouseClicked


    private void jTextFieldNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNombreFocusLost
        // TODO add your handling code here:
        //this.user.validarUsuario(this.jTextField1.getText());
    }//GEN-LAST:event_jTextFieldNombreFocusLost

    private void jTextFieldCedulaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCedulaFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCedulaFocusLost

    private void jTextFieldApellidoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldApellidoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldApellidoFocusLost

    private void jTextFieldApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldApellidoActionPerformed

    private void jDateChooserFechaNacimientoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jDateChooserFechaNacimientoFocusLost
        // TODO add your handling code here:

    }//GEN-LAST:event_jDateChooserFechaNacimientoFocusLost

    
    /**
     * @param args the command line arguments
     */
   //public static void  main(String[] a){
   //   new JFrameCrearPacienteSiNoExiste().setVisible(true);
  // }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBoxSangre;
    private javax.swing.JComboBox<String> jComboBoxSexo;
    private com.toedter.calendar.JDateChooser jDateChooserFechaNacimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextFieldApellido;
    private javax.swing.JTextField jTextFieldCedula;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables

}
