/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app.jframes;

import app.Classes.ClassHistorialPaciente;
import javax.swing.JOptionPane;

/**
 *
 * @author Eudy
 */
public class JFrameHistorialPaciente extends javax.swing.JFrame {

    /**
     * Creates new form ej
     */
    private int lineas = 10;
    private String id_patient,palabraBuscar="",id="";
    private conection.Mysql mysql;
    private app.Classes.ClassHistorialPaciente user ;
    
    
    public JFrameHistorialPaciente() {
        initComponents();
    }
    
    public JFrameHistorialPaciente(conection.Mysql mysql, String id_patient) {
       initComponents();
       this.id_patient = id_patient;
        this.mysql = mysql;
        user = new ClassHistorialPaciente(this.mysql,this.id_patient); 
        this.user.cargarDatoPaciente(this.jLabelNombreCompleto, this.jLabelCedula,this.jLabelFechaNacimiento, this.jLabelSexo, this.jLabelTipoSangre, this.jLabelEdad);
       // this.user.setId_patient(id_patient);
      // this.user.mostrarDatosTabla(jTable1,this.jLabel6);
      // this.jtable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jToolBar1 = new javax.swing.JToolBar();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableSonografia = new javax.swing.JTable();
        jToolBar4 = new javax.swing.JToolBar();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableSeguro = new javax.swing.JTable();
        jToolBar2 = new javax.swing.JToolBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTelefono = new javax.swing.JTable();
        jToolBar3 = new javax.swing.JToolBar();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableEmail = new javax.swing.JTable();
        jToolBar5 = new javax.swing.JToolBar();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableDireccion = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabelNombreCompleto = new javax.swing.JLabel();
        jLabelCedula = new javax.swing.JLabel();
        jLabelEdad = new javax.swing.JLabel();
        jLabelFechaNacimiento = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabelSexo = new javax.swing.JLabel();
        jLabelTipoSangre = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("HISTORIAL DEL PACIENTE");

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTabbedPane1MousePressed(evt);
            }
        });

        jToolBar1.setRollover(true);

        jTableSonografia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "CONDICION", "TIPO", "HOSPITAL", "ESTADO"
            }
        ));
        jScrollPane5.setViewportView(jTableSonografia);

        jToolBar1.add(jScrollPane5);

        jTabbedPane1.addTab("SONOGRAFIA", jToolBar1);

        jToolBar4.setRollover(true);

        jTableSeguro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "SEGURO", "NUMERO"
            }
        ));
        jScrollPane3.setViewportView(jTableSeguro);

        jToolBar4.add(jScrollPane3);

        jTabbedPane1.addTab("SEGURO", jToolBar4);

        jToolBar2.setRollover(true);
        jToolBar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jToolBar2MousePressed(evt);
            }
        });

        jTableTelefono.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "TIPO", "TELEFONO"
            }
        ));
        jScrollPane1.setViewportView(jTableTelefono);

        jToolBar2.add(jScrollPane1);

        jTabbedPane1.addTab("TELEFONO", jToolBar2);

        jToolBar3.setRollover(true);

        jTableEmail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "EMAIL"
            }
        ));
        jScrollPane2.setViewportView(jTableEmail);

        jToolBar3.add(jScrollPane2);

        jTabbedPane1.addTab("EMAIL", jToolBar3);

        jToolBar5.setRollover(true);

        jTableDireccion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "PROVINCIA", "SECTOR", "DIRECCION"
            }
        ));
        jScrollPane4.setViewportView(jTableDireccion);

        jToolBar5.add(jScrollPane4);

        jTabbedPane1.addTab("DIRECCION", jToolBar5);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("NOMBRE COMPLETO");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("CEDULLA");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("EDAD");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setText("SEXO");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setText("TIPO DE SANGRE");

        jLabelNombreCompleto.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabelNombreCompleto.setText("NOMBRE COMPLETO");

        jLabelCedula.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabelCedula.setText("CEDULLA");

        jLabelEdad.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabelEdad.setText("EDAD");

        jLabelFechaNacimiento.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabelFechaNacimiento.setText("EDAD");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel11.setText("FECHA NACIMIENTO");

        jLabelSexo.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabelSexo.setText("SEXO");

        jLabelTipoSangre.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabelTipoSangre.setText("TIPO DE SANGRE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabelNombreCompleto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelCedula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                    .addComponent(jLabelTipoSangre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelNombreCompleto))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCedula)
                            .addComponent(jLabelFechaNacimiento)
                            .addComponent(jLabelEdad))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSexo)
                    .addComponent(jLabelTipoSangre))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("HISTORIAL DEL PACIENTE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPane1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MousePressed
        // TODO add your handling code here:
        switch(this.jTabbedPane1.getTitleAt(this.jTabbedPane1.getSelectedIndex())){
            case "TELEFONO":
                this.user.mostrarDatosTablaTelefono(this.jTableTelefono);
            break;
            case "EMAIL":
                this.user.mostrarDatosTablaEmail(this.jTableEmail);
            break;
            case "SEGURO":
                this.user.mostrarDatosTablaSeguro(this.jTableSeguro);
            break;
            case "DIRECCION":
                this.user.mostrarDatosTablaDireccion(this.jTableDireccion);
            break;
        }
    }//GEN-LAST:event_jTabbedPane1MousePressed

    private void jToolBar2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToolBar2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToolBar2MousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelCedula;
    private javax.swing.JLabel jLabelEdad;
    private javax.swing.JLabel jLabelFechaNacimiento;
    private javax.swing.JLabel jLabelNombreCompleto;
    private javax.swing.JLabel jLabelSexo;
    private javax.swing.JLabel jLabelTipoSangre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableDireccion;
    private javax.swing.JTable jTableEmail;
    private javax.swing.JTable jTableSeguro;
    private javax.swing.JTable jTableSonografia;
    private javax.swing.JTable jTableTelefono;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JToolBar jToolBar3;
    private javax.swing.JToolBar jToolBar4;
    private javax.swing.JToolBar jToolBar5;
    // End of variables declaration//GEN-END:variables
}
