/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app.jframes;
import app.Classes.ClassBuscarSonografia;
/**
 *
 * @author Eudy
 */
import conection.Mysql;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class JFrameBuscarSonografia extends javax.swing.JFrame {

    
    private int lineas = 10;
    private String palabraBuscar="",id="";
    private conection.Mysql mysql;
    private ClassBuscarSonografia user ;
    private String usuarioID,nombreUsuario,nombreTituloUsuario;

    /**
     * Creates new form User
     */
    public JFrameBuscarSonografia() {
        initComponents();
       this.user.mostrarDatosTabla(jTable1,this.jLabel6);
      // this.jtable();
    }
    public JFrameBuscarSonografia(conection.Mysql mysql) {
       initComponents();
        this.mysql = mysql;
        user = new ClassBuscarSonografia(this.mysql); 
        //this.user.llenarComboBox(this.jComboBoxSangre);
        this.user.llenarComboBoxTipoSonografia(this.jComboBoxBuscarTipoSonografia);
        this.user.llenarComboBoxCondicionSonografia(this.jComboBoxBuscarCondicionSonografia);
        this.user.llenarComboBoxEstadoSonografia(this.jComboBoxBuscarEstadoSonografia);
        this.user.llenarComboBoxHospital(this.jComboBoxBuscarHospital);
        this.user.llenarComboBoxMedico(this.jComboBoxBuscarMedico);
        this.user.llenarComboBoxSexo(this.jComboBoxBuscarSexo);
        this.user.llenarComboBoxTipoSangre(jComboBoxBuscarTipoSangre);
        
        this.user.mostrarDatosTablaSonografia(this.jTable1,this.jLabel6);
        this.user.setjTabbedPane1(jTabbedPane1);
        //this.user.mostrarDatosTabla(jTable1,this.jLabel6);
        this.user.setTotal(jLabel6);
        this.user.setjTable1(jTable1);
       
      // this.jtable();
    }
    public void setDatosUsuario(String usuarioID, String nombreUsuario,String nombreTituloUsuario){
        this.usuarioID = usuarioID;
        this.nombreUsuario = nombreUsuario;
        this.nombreTituloUsuario = nombreTituloUsuario;
        //JOptionPane.showMessageDialog(null, "Usuario "+this.usuarioID+" "+this.nombreUsuario+" "+this.nombreTituloUsuario);
        this.user.setDatosUsuario(usuarioID, nombreUsuario, nombreTituloUsuario);
    }
    
    /*EJEMPLO SIMPLE PARA MOSTRAR DATOS EN UNA TABLA
    public void jtable(){
            JOptionPane.showMessageDialog(null, "Tabla");
           //DefaultTableModel modelo = (DefaultTableModel) this.jTable1.getModel();
           
           String[] titulos = {"id","usuario"};
           this.lineas = this.lineas + 2;
          //modelo.setColumnIdentifiers(titulos);
           
           Object[][] fila = new Object[this.lineas][2];
           for(int c = 0 ; c < this.lineas ; c++){
               System.out.println("---- x "+ c);
                //for(int i = 0 ; i < 2 ; i++){
                    fila[c][0] = "x "+ c+" y ";
                    //System.out.println("x "+ c+" y "+i);
                    fila[c][1]  = "Eudy";
                    //modelo.addRow(fila);
                //}
           }
          DefaultTableModel modelo = new DefaultTableModel(fila,titulos);
          this.jTable1.setModel(modelo);
    }*/
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        VerHistorico = new javax.swing.JMenuItem();
        EditarEliminarVerTelefono = new javax.swing.JMenuItem();
        EditarEliminarVerEmail = new javax.swing.JMenuItem();
        EditarEliminarVerDireccion = new javax.swing.JMenuItem();
        EditarEliminarVerSeguro = new javax.swing.JMenuItem();
        EliminarPaciente = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanelColummna1 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jTextFieldIDPaciente = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldBuscarCedula = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jTextFieldBuscarNoSeguro = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jTextFieldBuscarDireccionProvincia = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jTextFieldBuscarTelefono = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jTextFieldReferidoPor = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jTextFieldIDSonografia = new javax.swing.JTextField();
        jPanelColumna2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldBuscarNombre = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jComboBoxBuscarSexo = new javax.swing.JComboBox<>();
        jLabel28 = new javax.swing.JLabel();
        jTextFieldBuscarSectorDireccion = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jTextFieldBuscarEmail = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jTextFieldBuscarNombreSeguro = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldBuscarQueContenga = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jComboBoxBuscarCondicionSonografia = new javax.swing.JComboBox<>();
        jPanelColumna3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldBuscarApellido = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jDateChooseBuscarrFechaNacimiento = new com.toedter.calendar.JDateChooser();
        jLabel25 = new javax.swing.JLabel();
        jComboBoxBuscarTipoSangre = new javax.swing.JComboBox<>();
        jLabel31 = new javax.swing.JLabel();
        jTextFieldBuscarAdressDireccion = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jDateChooseBuscarrFechaSonografia = new com.toedter.calendar.JDateChooser();
        jLabel39 = new javax.swing.JLabel();
        jComboBoxBuscarEstadoSonografia = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jPanelColumna4 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jComboBoxBuscarHospital = new javax.swing.JComboBox<>();
        jLabel44 = new javax.swing.JLabel();
        jComboBoxBuscarMedico = new javax.swing.JComboBox<>();
        jLabel45 = new javax.swing.JLabel();
        jComboBoxBuscarTipoSonografia = new javax.swing.JComboBox<>();

        VerHistorico.setText("VerHistorico");
        VerHistorico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                VerHistoricoMousePressed(evt);
            }
        });
        jPopupMenu1.add(VerHistorico);

        EditarEliminarVerTelefono.setText("Editar / Eliminar / Ver Teléfono");
        EditarEliminarVerTelefono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                EditarEliminarVerTelefonoMousePressed(evt);
            }
        });
        jPopupMenu1.add(EditarEliminarVerTelefono);

        EditarEliminarVerEmail.setText("Editar / Eliminar / Ver Email");
        EditarEliminarVerEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                EditarEliminarVerEmailMousePressed(evt);
            }
        });
        jPopupMenu1.add(EditarEliminarVerEmail);

        EditarEliminarVerDireccion.setText("Editar / Eliminar / Ver Dirección");
        EditarEliminarVerDireccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                EditarEliminarVerDireccionMousePressed(evt);
            }
        });
        jPopupMenu1.add(EditarEliminarVerDireccion);

        EditarEliminarVerSeguro.setText("Editar / Eliminar / Ver Seguro");
        EditarEliminarVerSeguro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                EditarEliminarVerSeguroMousePressed(evt);
            }
        });
        jPopupMenu1.add(EditarEliminarVerSeguro);

        EliminarPaciente.setText("EliminarPaciente");
        EliminarPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                EliminarPacienteMousePressed(evt);
            }
        });
        jPopupMenu1.add(EliminarPaciente);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Busccador de Sonografia");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Buscar Sonografia");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setText("Total de sonografia");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setText("4000");

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Nombre de usuario"
            }
        ));
        jTable1.setComponentPopupMenu(jPopupMenu1);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(552, 552, 552))
            .addComponent(jScrollPane1)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Resultado de la busqueda", jPanel3);

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("Id Paciente");

        jTextFieldIDPaciente.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextFieldIDPaciente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldIDPacienteKeyPressed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Cedula Paciente");

        jTextFieldBuscarCedula.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextFieldBuscarCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldBuscarCedulaKeyPressed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("No. Seguro Paciente");

        jTextFieldBuscarNoSeguro.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextFieldBuscarNoSeguro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldBuscarNoSeguroKeyPressed(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Provincia Paciente");

        jTextFieldBuscarDireccionProvincia.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextFieldBuscarDireccionProvincia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldBuscarDireccionProvinciaKeyPressed(evt);
            }
        });

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("Teléfono Paciente");

        jTextFieldBuscarTelefono.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextFieldBuscarTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldBuscarTelefonoKeyPressed(evt);
            }
        });

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setText("Sonografia Referida por");

        jTextFieldReferidoPor.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextFieldReferidoPor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldReferidoPorKeyPressed(evt);
            }
        });

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setText("Id Sonografia");

        jTextFieldIDSonografia.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextFieldIDSonografia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldIDSonografiaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanelColummna1Layout = new javax.swing.GroupLayout(jPanelColummna1);
        jPanelColummna1.setLayout(jPanelColummna1Layout);
        jPanelColummna1Layout.setHorizontalGroup(
            jPanelColummna1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTextFieldBuscarNoSeguro)
            .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTextFieldBuscarDireccionProvincia)
            .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTextFieldBuscarTelefono)
            .addComponent(jTextFieldBuscarCedula)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTextFieldIDPaciente)
            .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTextFieldReferidoPor)
            .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTextFieldIDSonografia)
            .addComponent(jLabel36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelColummna1Layout.setVerticalGroup(
            jPanelColummna1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelColummna1Layout.createSequentialGroup()
                .addComponent(jLabel36)
                .addGap(6, 6, 6)
                .addComponent(jTextFieldIDSonografia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel35)
                .addGap(6, 6, 6)
                .addComponent(jTextFieldReferidoPor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel32)
                .addGap(6, 6, 6)
                .addComponent(jTextFieldIDPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel10)
                .addGap(6, 6, 6)
                .addComponent(jTextFieldBuscarCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel27)
                .addGap(10, 10, 10)
                .addComponent(jTextFieldBuscarNoSeguro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel29)
                .addGap(10, 10, 10)
                .addComponent(jTextFieldBuscarDireccionProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel33)
                .addGap(6, 6, 6)
                .addComponent(jTextFieldBuscarTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Nombres Paciente");

        jTextFieldBuscarNombre.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextFieldBuscarNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldBuscarNombreKeyPressed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Sexo Paciente");

        jComboBoxBuscarSexo.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jComboBoxBuscarSexo.setToolTipText("");

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Sector Paciente");

        jTextFieldBuscarSectorDireccion.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextFieldBuscarSectorDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldBuscarSectorDireccionKeyPressed(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("Email Paciente");

        jTextFieldBuscarEmail.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextFieldBuscarEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldBuscarEmailKeyPressed(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("Nombre Seguro Paciente");

        jTextFieldBuscarNombreSeguro.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextFieldBuscarNombreSeguro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldBuscarNombreSeguroKeyPressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Que Contenga");

        jTextFieldBuscarQueContenga.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextFieldBuscarQueContenga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldBuscarQueContengaKeyPressed(evt);
            }
        });

        jLabel38.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel38.setText("Condición Sonografia");

        jComboBoxBuscarCondicionSonografia.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jComboBoxBuscarCondicionSonografia.setToolTipText("");

        javax.swing.GroupLayout jPanelColumna2Layout = new javax.swing.GroupLayout(jPanelColumna2);
        jPanelColumna2.setLayout(jPanelColumna2Layout);
        jPanelColumna2Layout.setHorizontalGroup(
            jPanelColumna2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelColumna2Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(jPanelColumna2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldBuscarNombre, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldBuscarQueContenga)
                    .addComponent(jLabel38, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxBuscarCondicionSonografia, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jComboBoxBuscarSexo, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel34, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
            .addComponent(jTextFieldBuscarNombreSeguro, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTextFieldBuscarSectorDireccion, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jLabel30, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTextFieldBuscarEmail, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanelColumna2Layout.setVerticalGroup(
            jPanelColumna2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelColumna2Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldBuscarQueContenga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel38)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxBuscarCondicionSonografia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldBuscarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxBuscarSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel34)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldBuscarNombreSeguro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldBuscarSectorDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel30)
                .addGap(4, 4, 4)
                .addComponent(jTextFieldBuscarEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Apellidos Paciente");

        jTextFieldBuscarApellido.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextFieldBuscarApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldBuscarApellidoKeyPressed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Fecha Nacimiento Paciente");

        jDateChooseBuscarrFechaNacimiento.setDateFormatString("yyyy-MM-dd");
        jDateChooseBuscarrFechaNacimiento.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jDateChooseBuscarrFechaNacimiento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jDateChooseBuscarrFechaNacimientoKeyPressed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Tipo de sangre Paciente");

        jComboBoxBuscarTipoSangre.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jComboBoxBuscarTipoSangre.setToolTipText("");

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("Dirección Paciente");

        jTextFieldBuscarAdressDireccion.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextFieldBuscarAdressDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldBuscarAdressDireccionKeyPressed(evt);
            }
        });

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel37.setText("Fecha Sonografia");

        jDateChooseBuscarrFechaSonografia.setDateFormatString("yyyy-MM-dd");
        jDateChooseBuscarrFechaSonografia.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jDateChooseBuscarrFechaSonografia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jDateChooseBuscarrFechaSonografiaKeyPressed(evt);
            }
        });

        jLabel39.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel39.setText("Estado Sonografia");

        jComboBoxBuscarEstadoSonografia.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jComboBoxBuscarEstadoSonografia.setToolTipText("");

        javax.swing.GroupLayout jPanelColumna3Layout = new javax.swing.GroupLayout(jPanelColumna3);
        jPanelColumna3.setLayout(jPanelColumna3Layout);
        jPanelColumna3Layout.setHorizontalGroup(
            jPanelColumna3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jDateChooseBuscarrFechaNacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jComboBoxBuscarTipoSangre, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTextFieldBuscarAdressDireccion)
            .addComponent(jTextFieldBuscarApellido)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel37, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jDateChooseBuscarrFechaSonografia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel39, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jComboBoxBuscarEstadoSonografia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelColumna3Layout.setVerticalGroup(
            jPanelColumna3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelColumna3Layout.createSequentialGroup()
                .addComponent(jLabel37)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDateChooseBuscarrFechaSonografia, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel39)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxBuscarEstadoSonografia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldBuscarApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDateChooseBuscarrFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxBuscarTipoSangre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldBuscarAdressDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Buscar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jLabel41.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel41.setText("Hospital");

        jComboBoxBuscarHospital.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jComboBoxBuscarHospital.setToolTipText("");

        jLabel44.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel44.setText("Medico");

        jComboBoxBuscarMedico.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jComboBoxBuscarMedico.setToolTipText("");

        jLabel45.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel45.setText("Tipo Sonografia");

        jComboBoxBuscarTipoSonografia.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jComboBoxBuscarTipoSonografia.setToolTipText("");

        javax.swing.GroupLayout jPanelColumna4Layout = new javax.swing.GroupLayout(jPanelColumna4);
        jPanelColumna4.setLayout(jPanelColumna4Layout);
        jPanelColumna4Layout.setHorizontalGroup(
            jPanelColumna4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel41, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jComboBoxBuscarHospital, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel44, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jComboBoxBuscarMedico, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel45, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
            .addComponent(jComboBoxBuscarTipoSonografia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelColumna4Layout.setVerticalGroup(
            jPanelColumna4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelColumna4Layout.createSequentialGroup()
                .addComponent(jLabel45)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxBuscarTipoSonografia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel44)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jComboBoxBuscarMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel41)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxBuscarHospital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(237, 237, 237))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanelColummna1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelColumna2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelColumna3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelColumna4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanelColumna4, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanelColummna1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanelColumna2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanelColumna3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1))
        );

        jTabbedPane1.addTab("Opciones Busqueda", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int select = this.jTable1.rowAtPoint(evt.getPoint());
        String id = this.jTable1.getValueAt(select, 0).toString();
        this.user.mostrarSonografiaPDF(id);
        //int select = this.jTable1.rowAtPoint(evt.getPoint());
        //String id = this.jTable1.getValueAt(select, 0).toString();
        //this.id = id;
        //System.out.println("Click editar registro "+id);
       // String[] respuesta = this.user.mostrarEditarPaciente(id);
        //this.user.cambiarTestoParaEditar(this.jButton1,this.jLabel9,this.jTextFieldNombre);
        
        //this.jTextFieldNombre.setText(respuesta[1]);
        //this.jTextFieldCedula.setText(respuesta[3]);
        //this.jTextField4.setText(respuesta[4]);
        //this.jTextFieldApellido.setText(respuesta[2]);
        //this.jComboBoxSexo.setSelectedItem(respuesta[5]);
        //this.jTextArea1.setText(respuesta[6]);
    }//GEN-LAST:event_jTable1MouseClicked

    private void EliminarPacienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EliminarPacienteMousePressed
        // TODO add your handling code here:
        // TODO add your handling code here:
         // TODO add your handling code here:
        int fila = this.jTable1.getSelectedRow();
         
        String id = this.jTable1.getValueAt(fila, 0).toString();
        String user = this.jTable1.getValueAt(fila, 0).toString();
        
        this.id = id;
        int respuesta = JOptionPane.showConfirmDialog(null, "Desea eliminar este registro?", "Eliminar registro", JOptionPane.YES_NO_OPTION);
        if(respuesta == JOptionPane.YES_OPTION){
            boolean eliminado = this.user.elimnar(id);
            if(eliminado){
                JOptionPane.showMessageDialog(null, "Se elimino correctamente el registro.");
                this.user.mostrarDatosTabla(this.jTable1, this.jLabel6);
                this.user.setAgregar(true);
                //this.user.cambiarTestoParaEditar(this.jButton1,this.jLabel9,this.jTextFieldNombre);
                //this.user.limpiarTexto(this.jTextFieldNombre, this.jTextFieldApellido,this.jTextFieldTelefonoCelular,this.jTextFieldEmail2,this.jTextFieldCedula,this.jTextFieldTelefonoCasa,this.jTextFieldProvincia,this.jTextFieldSector,this.jTextFieldDireccion,this.jComboBoxSexo,this.jComboBoxSangre,this.jTextFieldNombreSeguro,this.jTextFieldNumeroSeguro,this.jDateChooserFechaNacimiento,this.jTextFieldTelefonoTrabajo,this.jTextFieldEmail1);

            }else{
                 JOptionPane.showMessageDialog(null, "No se pudo eliminar correctamente el registro.");           
            }
        }
        System.out.println("prueba "+id+" prueba ");
    }//GEN-LAST:event_EliminarPacienteMousePressed

    private void EditarEliminarVerEmailMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditarEliminarVerEmailMousePressed
        // TODO add your handling code here:
        int fila = this.jTable1.getSelectedRow();
        String id_patient = this.jTable1.getValueAt(fila, 0).toString();
        new JFrameEmail(mysql,id_patient,this.usuarioID,this.nombreUsuario,this.nombreTituloUsuario).setVisible(true);
    }//GEN-LAST:event_EditarEliminarVerEmailMousePressed

    private void EditarEliminarVerSeguroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditarEliminarVerSeguroMousePressed
        // TODO add your handling code here:
        int fila = this.jTable1.getSelectedRow();
        String id_patient = this.jTable1.getValueAt(fila, 0).toString();
        new JFrameSeguro(mysql,id_patient,this.usuarioID,this.nombreUsuario,this.nombreTituloUsuario).setVisible(true);
                                                     
    }//GEN-LAST:event_EditarEliminarVerSeguroMousePressed

    private void EditarEliminarVerDireccionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditarEliminarVerDireccionMousePressed
        // TODO add your handling code here:
        int fila = this.jTable1.getSelectedRow();
        String id_patient = this.jTable1.getValueAt(fila, 0).toString();
        new JFrameDireccion(mysql,id_patient,this.usuarioID,this.nombreUsuario,this.nombreTituloUsuario).setVisible(true);
    }//GEN-LAST:event_EditarEliminarVerDireccionMousePressed

    private void EditarEliminarVerTelefonoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditarEliminarVerTelefonoMousePressed
        // TODO add your handling code here:
         int fila = this.jTable1.getSelectedRow();
        String id_patient = this.jTable1.getValueAt(fila, 0).toString();
        new JFrameTelefono(mysql,id_patient,this.usuarioID,this.nombreUsuario,this.nombreTituloUsuario).setVisible(true);
        
    }//GEN-LAST:event_EditarEliminarVerTelefonoMousePressed

    private void VerHistoricoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VerHistoricoMousePressed
        // TODO add your handling code here:
        int fila = this.jTable1.getSelectedRow();
        String id_patient = this.jTable1.getValueAt(fila, 0).toString();
        new JFrameHistorialPaciente(mysql,id_patient).setVisible(true);
    }//GEN-LAST:event_VerHistoricoMousePressed

    private void jTextFieldIDPacienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldIDPacienteKeyPressed
        // TODO add your handling code here:
        this.user.buscadorEnter(evt, 1, this.jTextFieldIDPaciente.getText());
    }//GEN-LAST:event_jTextFieldIDPacienteKeyPressed

    private void jTextFieldBuscarNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBuscarNombreKeyPressed
        // TODO add your handling code here:
        this.user.buscadorEnter(evt, 2, this.jTextFieldBuscarNombre.getText());
    }//GEN-LAST:event_jTextFieldBuscarNombreKeyPressed

    private void jTextFieldBuscarApellidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBuscarApellidoKeyPressed
        // TODO add your handling code here:
       this.user.buscadorEnter(evt, 3, this.jTextFieldBuscarApellido.getText());
    }//GEN-LAST:event_jTextFieldBuscarApellidoKeyPressed

    private void jTextFieldBuscarCedulaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBuscarCedulaKeyPressed
        // TODO add your handling code here:
        this.user.buscadorEnter(evt, 4, this.jTextFieldBuscarCedula.getText());

    }//GEN-LAST:event_jTextFieldBuscarCedulaKeyPressed

    private void jDateChooseBuscarrFechaNacimientoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jDateChooseBuscarrFechaNacimientoKeyPressed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "evento press activo");
       String fecha_nacimiento = ((javax.swing.JTextField)this.jDateChooseBuscarrFechaNacimiento.getDateEditor().getUiComponent()).getText();
        this.user.buscadorEnter(evt, 5, fecha_nacimiento);
    }//GEN-LAST:event_jDateChooseBuscarrFechaNacimientoKeyPressed

    private void jTextFieldBuscarNoSeguroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBuscarNoSeguroKeyPressed
        // TODO add your handling code here:
        this.user.buscadorEnter(evt, 8, this.jTextFieldBuscarNoSeguro.getText());
    }//GEN-LAST:event_jTextFieldBuscarNoSeguroKeyPressed

    private void jTextFieldBuscarSectorDireccionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBuscarSectorDireccionKeyPressed
        // TODO add your handling code here:
        this.user.buscadorEnter(evt, 7, this.jTextFieldBuscarSectorDireccion.getText());        
    }//GEN-LAST:event_jTextFieldBuscarSectorDireccionKeyPressed

    private void jTextFieldBuscarTelefonoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBuscarTelefonoKeyPressed
        // TODO add your handling code here:
        this.user.buscadorEnter(evt, 6, this.jTextFieldBuscarTelefono.getText());
    }//GEN-LAST:event_jTextFieldBuscarTelefonoKeyPressed

    private void jTextFieldBuscarDireccionProvinciaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBuscarDireccionProvinciaKeyPressed
        // TODO add your handling code here:
        this.user.buscadorEnter(evt, 9, this.jTextFieldBuscarDireccionProvincia.getText());
    }//GEN-LAST:event_jTextFieldBuscarDireccionProvinciaKeyPressed

    private void jTextFieldBuscarEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBuscarEmailKeyPressed
        // TODO add your handling code here:
        this.user.buscadorEnter(evt, 10, this.jTextFieldBuscarEmail.getText());
    }//GEN-LAST:event_jTextFieldBuscarEmailKeyPressed

    private void jTextFieldBuscarAdressDireccionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBuscarAdressDireccionKeyPressed
        // TODO add your handling code here:
        this.user.buscadorEnter(evt, 11, this.jTextFieldBuscarAdressDireccion.getText());        
    }//GEN-LAST:event_jTextFieldBuscarAdressDireccionKeyPressed

    private void jTextFieldBuscarNombreSeguroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBuscarNombreSeguroKeyPressed
        // TODO add your handling code here:
        this.user.buscadorEnter(evt, 12, this.jTextFieldBuscarNombreSeguro.getText());
    }//GEN-LAST:event_jTextFieldBuscarNombreSeguroKeyPressed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        String sexo = this.jComboBoxBuscarSexo.getSelectedItem().toString().toLowerCase();
        String tipo_sangre = "",tipo_sonografia ="",idMedico="",idHospital="";
        System.out.println(this.jComboBoxBuscarTipoSangre.getSelectedIndex());
        if(this.jComboBoxBuscarTipoSangre.getSelectedIndex() != 0){
            tipo_sangre = this.user.getIdTipoSangre(this.jComboBoxBuscarTipoSangre.getSelectedIndex()-1);
        }
        if(this.jComboBoxBuscarTipoSonografia.getSelectedIndex() != 0){
            tipo_sonografia = this.user.getIdTipoSonografia(this.jComboBoxBuscarTipoSonografia.getSelectedIndex()-1);
        }
        if(this.jComboBoxBuscarMedico.getSelectedIndex() != 0){
            idMedico = this.user.getIdMedico(this.jComboBoxBuscarMedico.getSelectedIndex()-1);
        }
        if(this.jComboBoxBuscarHospital.getSelectedIndex() != 0){
            idHospital = this.user.getIdHospital(this.jComboBoxBuscarHospital.getSelectedIndex()-1);
        }
        String fecha_nacimiento = ((javax.swing.JTextField)this.jDateChooseBuscarrFechaNacimiento.getDateEditor().getUiComponent()).getText();
        String fecha_sonografia = ((javax.swing.JTextField)this.jDateChooseBuscarrFechaSonografia.getDateEditor().getUiComponent()).getText();

        this.user.crearBusqueda(this.jTextFieldIDPaciente.getText(),this.jTextFieldBuscarNombre.getText(),this.jTextFieldBuscarApellido.getText(),this.jTextFieldBuscarCedula.getText(),fecha_nacimiento,sexo,this.jTextFieldBuscarEmail.getText(),this.jTextFieldBuscarTelefono.getText(),this.jTextFieldBuscarDireccionProvincia.getText(),this.jTextFieldBuscarSectorDireccion.getText(),this.jTextFieldBuscarAdressDireccion.getText(),this.jTextFieldBuscarNoSeguro.getText(),this.jTextFieldBuscarNombreSeguro.getText(),tipo_sangre,this.jTextFieldIDSonografia.getText(),this.jTextFieldReferidoPor.getText(),this.jTextFieldBuscarQueContenga.getText(),this.jComboBoxBuscarCondicionSonografia.getSelectedItem().toString(),fecha_sonografia,this.jComboBoxBuscarEstadoSonografia.getSelectedItem().toString(),tipo_sonografia,idMedico,idHospital);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jTextFieldReferidoPorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldReferidoPorKeyPressed
        // TODO add your handling code here:
        this.user.buscadorEnter(evt, 15, this.jTextFieldReferidoPor.getText());
    }//GEN-LAST:event_jTextFieldReferidoPorKeyPressed

    private void jTextFieldIDSonografiaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldIDSonografiaKeyPressed
        // TODO add your handling code here:
        this.user.buscadorEnter(evt, 13, this.jTextFieldIDSonografia.getText());
    }//GEN-LAST:event_jTextFieldIDSonografiaKeyPressed

    private void jTextFieldBuscarQueContengaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBuscarQueContengaKeyPressed
        // TODO add your handling code here:
        this.user.buscadorEnter(evt, 14, this.jTextFieldBuscarQueContenga.getText());
    }//GEN-LAST:event_jTextFieldBuscarQueContengaKeyPressed

    private void jDateChooseBuscarrFechaSonografiaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jDateChooseBuscarrFechaSonografiaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDateChooseBuscarrFechaSonografiaKeyPressed

    
    /**
     * @param args the command line arguments
     */
   //public static void  main(String[] a){
   //   new JFrameBuscarSonografia().setVisible(true);
  // }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem EditarEliminarVerDireccion;
    private javax.swing.JMenuItem EditarEliminarVerEmail;
    private javax.swing.JMenuItem EditarEliminarVerSeguro;
    private javax.swing.JMenuItem EditarEliminarVerTelefono;
    private javax.swing.JMenuItem EliminarPaciente;
    private javax.swing.JMenuItem VerHistorico;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBoxBuscarCondicionSonografia;
    private javax.swing.JComboBox<String> jComboBoxBuscarEstadoSonografia;
    private javax.swing.JComboBox<String> jComboBoxBuscarHospital;
    private javax.swing.JComboBox<String> jComboBoxBuscarMedico;
    private javax.swing.JComboBox<String> jComboBoxBuscarSexo;
    private javax.swing.JComboBox<String> jComboBoxBuscarTipoSangre;
    private javax.swing.JComboBox<String> jComboBoxBuscarTipoSonografia;
    private com.toedter.calendar.JDateChooser jDateChooseBuscarrFechaNacimiento;
    private com.toedter.calendar.JDateChooser jDateChooseBuscarrFechaSonografia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelColummna1;
    private javax.swing.JPanel jPanelColumna2;
    private javax.swing.JPanel jPanelColumna3;
    private javax.swing.JPanel jPanelColumna4;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldBuscarAdressDireccion;
    private javax.swing.JTextField jTextFieldBuscarApellido;
    private javax.swing.JTextField jTextFieldBuscarCedula;
    private javax.swing.JTextField jTextFieldBuscarDireccionProvincia;
    private javax.swing.JTextField jTextFieldBuscarEmail;
    private javax.swing.JTextField jTextFieldBuscarNoSeguro;
    private javax.swing.JTextField jTextFieldBuscarNombre;
    private javax.swing.JTextField jTextFieldBuscarNombreSeguro;
    private javax.swing.JTextField jTextFieldBuscarQueContenga;
    private javax.swing.JTextField jTextFieldBuscarSectorDireccion;
    private javax.swing.JTextField jTextFieldBuscarTelefono;
    private javax.swing.JTextField jTextFieldIDPaciente;
    private javax.swing.JTextField jTextFieldIDSonografia;
    private javax.swing.JTextField jTextFieldReferidoPor;
    // End of variables declaration//GEN-END:variables

}
