/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app.jframes;

import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Eudy
 */
public class JFrameSelectVistaBuscadorPaciente extends javax.swing.JFrame {

    private JFrameCrearSonografia padre;
    private conection.Mysql mysql;

    /**
     * Creates new form JFrameSelectVistaBuscadorPaciente
     */
    public JFrameSelectVistaBuscadorPaciente(conection.Mysql mysql) {
        initComponents();
        this.mysql = mysql;
    }
    
    public void setPadre(JFrameCrearSonografia padre){
        this.padre = padre;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Seleccionar paciente");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Click en el paciente que desea seleccionar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int select = this.jTable1.rowAtPoint(evt.getPoint());
        String id = this.jTable1.getValueAt(select, 0).toString();
        String nombreCompleto = this.jTable1.getValueAt(select, 1).toString() +" "+this.jTable1.getValueAt(select, 2).toString();
        String TipoDeSangrePaciente = this.jTable1.getValueAt(select, 6).toString();
        String EdadPaciente = this.jTable1.getValueAt(select, 7).toString();
        String SexoPaciente = this.jTable1.getValueAt(select, 5).toString();
        String CedulaPaciente = this.jTable1.getValueAt(select, 5).toString();


        this.padre.setInfoPacienteBuscado(id,nombreCompleto,TipoDeSangrePaciente,EdadPaciente,SexoPaciente,CedulaPaciente);
        this.dispose();
    }//GEN-LAST:event_jTable1MouseClicked

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

public void mostrarDatosTablaPorCedula(String buscar){
        String[] datos = {"t.id","t.name_patient","t.last_patient","t.document_id","t.date_of_birth"
                ,"t.sex","t1.name_of_blood","edad"};
        String select = "t.id,t.name_patient,t.last_patient,t.document_id,t.date_of_birth,t.sex,t1.name_of_blood,(CURDATE() -t.date_of_birth) as edad";
        String where = "t.document_id = '"+buscar+"' and ";
        String tablasJoin = "patient as t left join type_of_blood as t1 on "
                + "t.type_of_blood_id = t1.id";
        Object[][] resultado = (Object[][]) this.mysql.generarSelectMultipleTabla(tablasJoin, datos,select,where,"t.");
        //Object[][] resultado = (Object[][]) this.mysql.generarSelect("type_of_blood", datos);
        Object[][] infoTabla= (Object[][]) resultado[0][0];
        DefaultTableModel modelo = new DefaultTableModel(infoTabla,datos);
        this.jTable1.setModel(modelo);
    }
public void mostrarDatosTablaPorNombre(String buscar){
        String[] datos = {"t.id","t.name_patient","t.last_patient","t.document_id","t.date_of_birth"
                ,"t.sex","t1.name_of_blood","edad"};
        String select = "t.id,t.name_patient,t.last_patient,t.document_id,t.date_of_birth,t.sex,t1.name_of_blood,(CURDATE() -t.date_of_birth) as edad";
        String where = "t.name_patient like '%"+buscar+"%' and ";
        String tablasJoin = "patient as t left join type_of_blood as t1 on "
                + "t.type_of_blood_id = t1.id";
        Object[][] resultado = (Object[][]) this.mysql.generarSelectMultipleTabla(tablasJoin, datos,select,where,"t.");
        //Object[][] resultado = (Object[][]) this.mysql.generarSelect("type_of_blood", datos);
        Object[][] infoTabla= (Object[][]) resultado[0][0];
        DefaultTableModel modelo = new DefaultTableModel(infoTabla,datos);
        this.jTable1.setModel(modelo);
    }
public void mostrarDatosTablaPorApellido(String buscar){
        String[] datos = {"t.id","t.name_patient","t.last_patient","t.document_id","t.date_of_birth"
                ,"t.sex","t1.name_of_blood","edad"};
        String select = "t.id,t.name_patient,t.last_patient,t.document_id,t.date_of_birth,t.sex,t1.name_of_blood,(CURDATE() -t.date_of_birth) as edad";
        String where = "t.last_patient like '%"+buscar+"%' and ";
        String tablasJoin = "patient as t left join type_of_blood as t1 on "
                + "t.type_of_blood_id = t1.id";
        Object[][] resultado = (Object[][]) this.mysql.generarSelectMultipleTabla(tablasJoin, datos,select,where,"t.");
        //Object[][] resultado = (Object[][]) this.mysql.generarSelect("type_of_blood", datos);
        Object[][] infoTabla= (Object[][]) resultado[0][0];
        DefaultTableModel modelo = new DefaultTableModel(infoTabla,datos);
        this.jTable1.setModel(modelo);
    }
public void mostrarDatosTablaPorNombreCompleto(String buscar){
        String[] datos = {"t.id","t.name_patient","t.last_patient","t.document_id","t.date_of_birth"
                ,"t.sex","t1.name_of_blood","edad"};
        String select = "t.id,t.name_patient,t.last_patient,t.document_id,t.date_of_birth,t.sex,t1.name_of_blood,(CURDATE() -t.date_of_birth) as edad";
        String where = "CONCAT(t.name_patient,' ',t.last_patient) like '%"+buscar+"%' and ";
        String tablasJoin = "patient as t left join type_of_blood as t1 on "
                + "t.type_of_blood_id = t1.id";
        Object[][] resultado = (Object[][]) this.mysql.generarSelectMultipleTabla(tablasJoin, datos,select,where,"t.");
        //Object[][] resultado = (Object[][]) this.mysql.generarSelect("type_of_blood", datos);
        Object[][] infoTabla= (Object[][]) resultado[0][0];
        DefaultTableModel modelo = new DefaultTableModel(infoTabla,datos);
        this.jTable1.setModel(modelo);
    }
public void mostrarDatosTablaPorTelefono(String buscar){
        String[] datos = {"t.id","t.name_patient","t.last_patient","t.document_id","t.date_of_birth"
                ,"t.sex","t1.name_of_blood","edad"};
        String select = "t.id,t.name_patient,t.last_patient,t.document_id,t.date_of_birth,t.sex,t1.name_of_blood,(CURDATE() -t.date_of_birth) as edad";
        String where = "t2.telephone like '%"+buscar+"%' and ";
        String tablasJoin = "patient as t left join type_of_blood as t1 on "
                + "t.type_of_blood_id = t1.id"
                + " left join telephone as t2 on t.id = t2.id_patient";
        Object[][] resultado = (Object[][]) this.mysql.generarSelectMultipleTabla(tablasJoin, datos,select,where,"t.");
        //Object[][] resultado = (Object[][]) this.mysql.generarSelect("type_of_blood", datos);
        Object[][] infoTabla= (Object[][]) resultado[0][0];
        DefaultTableModel modelo = new DefaultTableModel(infoTabla,datos);
        this.jTable1.setModel(modelo);
    }

public void mostrarDatosTablaPorEmail(String buscar){
        String[] datos = {"t.id","t.name_patient","t.last_patient","t.document_id","t.date_of_birth"
                ,"t.sex","t1.name_of_blood","edad"};
        String select = "t.id,t.name_patient,t.last_patient,t.document_id,t.date_of_birth,t.sex,t1.name_of_blood,(CURDATE() -t.date_of_birth) as edad";
        String where = "t2.email like '%"+buscar+"%' and ";
        String tablasJoin = "patient as t left join type_of_blood as t1 on "
                + "t.type_of_blood_id = t1.id"
                + " left join email as t2 on t.id = t2.id_patient";
        Object[][] resultado = (Object[][]) this.mysql.generarSelectMultipleTabla(tablasJoin, datos,select,where,"t.");
        //Object[][] resultado = (Object[][]) this.mysql.generarSelect("type_of_blood", datos);
        Object[][] infoTabla= (Object[][]) resultado[0][0];
        DefaultTableModel modelo = new DefaultTableModel(infoTabla,datos);
        this.jTable1.setModel(modelo);
    }

public void mostrarDatosTablaPorSeguro(String buscar){
        String[] datos = {"t.id","t.name_patient","t.last_patient","t.document_id","t.date_of_birth"
                ,"t.sex","t1.name_of_blood","edad"};
        String select = "t.id,t.name_patient,t.last_patient,t.document_id,t.date_of_birth,t.sex,t1.name_of_blood,(CURDATE() -t.date_of_birth) as edad";
        String where = "t2.insurance_number = '"+buscar+"' and ";
        String tablasJoin = "patient as t left join type_of_blood as t1 on "
                + "t.type_of_blood_id = t1.id"
                + " left join insurance_patient as t2 on t.id = t2.id_patient";
        Object[][] resultado = (Object[][]) this.mysql.generarSelectMultipleTabla(tablasJoin, datos,select,where,"t.");
        //Object[][] resultado = (Object[][]) this.mysql.generarSelect("type_of_blood", datos);
        Object[][] infoTabla= (Object[][]) resultado[0][0];
        DefaultTableModel modelo = new DefaultTableModel(infoTabla,datos);
        this.jTable1.setModel(modelo);
    }

}
