/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app.jframes;
import app.Classes.ClassBuscarPaciente;
/**
 *
 * @author Eudy
 */
import conection.Mysql;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class JFrameBuscarPaciente extends javax.swing.JFrame {

    
    private int lineas = 10;
    private String palabraBuscar="",id="";
    private conection.Mysql mysql;
    private ClassBuscarPaciente user ;
    private String usuarioID,nombreUsuario,nombreTituloUsuario;

    /**
     * Creates new form User
     */
    public JFrameBuscarPaciente() {
        initComponents();
       this.user.mostrarDatosTabla(jTable1,this.jLabel6);
      // this.jtable();
    }
    public JFrameBuscarPaciente(conection.Mysql mysql) {
       initComponents();
        this.mysql = mysql;
        user = new ClassBuscarPaciente(this.mysql); 
        this.user.llenarComboBox(this.jComboBoxSangre);
        this.user.llenarComboBox(this.jComboBoxBuscarTipoSangre,"");
        this.user.mostrarDatosTabla(jTable1,this.jLabel6);
        this.user.setTotal(jLabel6);
        this.user.setjTable1(jTable1);
       
      // this.jtable();
    }
    public void setDatosUsuario(String usuarioID, String nombreUsuario,String nombreTituloUsuario){
        this.usuarioID = usuarioID;
        this.nombreUsuario = nombreUsuario;
        this.nombreTituloUsuario = nombreTituloUsuario;
        //JOptionPane.showMessageDialog(null, "Usuario "+this.usuarioID+" "+this.nombreUsuario+" "+this.nombreTituloUsuario);
        this.user.setDatosUsuario(usuarioID, nombreUsuario, nombreTituloUsuario);
    }
    
    /*EJEMPLO SIMPLE PARA MOSTRAR DATOS EN UNA TABLA
    public void jtable(){
            JOptionPane.showMessageDialog(null, "Tabla");
           //DefaultTableModel modelo = (DefaultTableModel) this.jTable1.getModel();
           
           String[] titulos = {"id","usuario"};
           this.lineas = this.lineas + 2;
          //modelo.setColumnIdentifiers(titulos);
           
           Object[][] fila = new Object[this.lineas][2];
           for(int c = 0 ; c < this.lineas ; c++){
               System.out.println("---- x "+ c);
                //for(int i = 0 ; i < 2 ; i++){
                    fila[c][0] = "x "+ c+" y ";
                    //System.out.println("x "+ c+" y "+i);
                    fila[c][1]  = "Eudy";
                    //modelo.addRow(fila);
                //}
           }
          DefaultTableModel modelo = new DefaultTableModel(fila,titulos);
          this.jTable1.setModel(modelo);
    }*/
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        VerHistorico = new javax.swing.JMenuItem();
        EditarEliminarVerTelefono = new javax.swing.JMenuItem();
        EditarEliminarVerEmail = new javax.swing.JMenuItem();
        EditarEliminarVerDireccion = new javax.swing.JMenuItem();
        EditarEliminarVerSeguro = new javax.swing.JMenuItem();
        EliminarPaciente = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanelColummna1 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jTextFieldIDPaciente = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldBuscarCedula = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jTextFieldBuscarNoSeguro = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jTextFieldBuscarDireccionProvincia = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jTextFieldBuscarTelefono = new javax.swing.JTextField();
        jPanelColumna2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldBuscarNombre = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jComboBoxBuscarSexo = new javax.swing.JComboBox<>();
        jLabel28 = new javax.swing.JLabel();
        jTextFieldBuscarSectorDireccion = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jTextFieldBuscarEmail = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jTextFieldBuscarNombreSeguro = new javax.swing.JTextField();
        jPanelColumna3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldBuscarApellido = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jDateChooseBuscarrFechaNacimiento = new com.toedter.calendar.JDateChooser();
        jLabel25 = new javax.swing.JLabel();
        jComboBoxBuscarTipoSangre = new javax.swing.JComboBox<>();
        jLabel31 = new javax.swing.JLabel();
        jTextFieldBuscarAdressDireccion = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jTextFieldTelefonoCelular = new javax.swing.JTextField();
        jTextFieldTelefonoTrabajo = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldEmail1 = new javax.swing.JTextField();
        jTextFieldEmail2 = new javax.swing.JTextField();
        jDateChooserFechaNacimiento = new com.toedter.calendar.JDateChooser();
        jLabel14 = new javax.swing.JLabel();
        jComboBoxSexo = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jComboBoxSangre = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextFieldProvincia = new javax.swing.JTextField();
        jTextFieldSector = new javax.swing.JTextField();
        jTextFieldDireccion = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextFieldTelefonoCasa = new javax.swing.JTextField();
        jTextFieldNombreSeguro = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNumeroSeguro = new javax.swing.JTextField();
        jTextFieldCedula = new javax.swing.JTextField();
        jTextFieldApellido = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        VerHistorico.setText("VerHistorico");
        VerHistorico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                VerHistoricoMousePressed(evt);
            }
        });
        jPopupMenu1.add(VerHistorico);

        EditarEliminarVerTelefono.setText("Editar / Eliminar / Ver Teléfono");
        EditarEliminarVerTelefono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                EditarEliminarVerTelefonoMousePressed(evt);
            }
        });
        jPopupMenu1.add(EditarEliminarVerTelefono);

        EditarEliminarVerEmail.setText("Editar / Eliminar / Ver Email");
        EditarEliminarVerEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                EditarEliminarVerEmailMousePressed(evt);
            }
        });
        jPopupMenu1.add(EditarEliminarVerEmail);

        EditarEliminarVerDireccion.setText("Editar / Eliminar / Ver Dirección");
        EditarEliminarVerDireccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                EditarEliminarVerDireccionMousePressed(evt);
            }
        });
        jPopupMenu1.add(EditarEliminarVerDireccion);

        EditarEliminarVerSeguro.setText("Editar / Eliminar / Ver Seguro");
        EditarEliminarVerSeguro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                EditarEliminarVerSeguroMousePressed(evt);
            }
        });
        jPopupMenu1.add(EditarEliminarVerSeguro);

        EliminarPaciente.setText("EliminarPaciente");
        EliminarPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                EliminarPacienteMousePressed(evt);
            }
        });
        jPopupMenu1.add(EliminarPaciente);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Busccador de Paciente");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Buscar Paciente");

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Nombre de usuario"
            }
        ));
        jTable1.setComponentPopupMenu(jPopupMenu1);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setText("Total de paciente");

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("Id Paciente");

        jTextFieldIDPaciente.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextFieldIDPaciente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldIDPacienteKeyPressed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Cedula");

        jTextFieldBuscarCedula.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextFieldBuscarCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldBuscarCedulaKeyPressed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("No. Seguro");

        jTextFieldBuscarNoSeguro.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextFieldBuscarNoSeguro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldBuscarNoSeguroKeyPressed(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Provincia");

        jTextFieldBuscarDireccionProvincia.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextFieldBuscarDireccionProvincia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldBuscarDireccionProvinciaKeyPressed(evt);
            }
        });

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("Teléfono");

        jTextFieldBuscarTelefono.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextFieldBuscarTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldBuscarTelefonoKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanelColummna1Layout = new javax.swing.GroupLayout(jPanelColummna1);
        jPanelColummna1.setLayout(jPanelColummna1Layout);
        jPanelColummna1Layout.setHorizontalGroup(
            jPanelColummna1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelColummna1Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanelColummna1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(jTextFieldBuscarNoSeguro)
                    .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldBuscarDireccionProvincia)
                    .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldBuscarTelefono)
                    .addGroup(jPanelColummna1Layout.createSequentialGroup()
                        .addGroup(jPanelColummna1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldIDPaciente)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldBuscarCedula))
                        .addGap(2, 2, 2)))
                .addGap(2, 2, 2))
        );
        jPanelColummna1Layout.setVerticalGroup(
            jPanelColummna1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelColummna1Layout.createSequentialGroup()
                .addComponent(jLabel32)
                .addGap(6, 6, 6)
                .addComponent(jTextFieldIDPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel10)
                .addGap(6, 6, 6)
                .addComponent(jTextFieldBuscarCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel27)
                .addGap(10, 10, 10)
                .addComponent(jTextFieldBuscarNoSeguro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel29)
                .addGap(10, 10, 10)
                .addComponent(jTextFieldBuscarDireccionProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel33)
                .addGap(6, 6, 6)
                .addComponent(jTextFieldBuscarTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Nombres");

        jTextFieldBuscarNombre.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextFieldBuscarNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldBuscarNombreKeyPressed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Sexo");

        jComboBoxBuscarSexo.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jComboBoxBuscarSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "MASCULINO", "FEMENINO" }));
        jComboBoxBuscarSexo.setToolTipText("");

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Sector");

        jTextFieldBuscarSectorDireccion.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextFieldBuscarSectorDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldBuscarSectorDireccionKeyPressed(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("Email");

        jTextFieldBuscarEmail.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextFieldBuscarEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldBuscarEmailKeyPressed(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("Nombre Seguro");

        jTextFieldBuscarNombreSeguro.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextFieldBuscarNombreSeguro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldBuscarNombreSeguroKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanelColumna2Layout = new javax.swing.GroupLayout(jPanelColumna2);
        jPanelColumna2.setLayout(jPanelColumna2Layout);
        jPanelColumna2Layout.setHorizontalGroup(
            jPanelColumna2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelColumna2Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(jPanelColumna2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel34, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldBuscarNombreSeguro)
                    .addGroup(jPanelColumna2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanelColumna2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldBuscarNombre))
                        .addGap(1, 1, 1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelColumna2Layout.createSequentialGroup()
                        .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(3, 3, 3))
                    .addComponent(jComboBoxBuscarSexo, 0, 232, Short.MAX_VALUE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldBuscarEmail)))
            .addComponent(jTextFieldBuscarSectorDireccion)
            .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelColumna2Layout.setVerticalGroup(
            jPanelColumna2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelColumna2Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addGap(6, 6, 6)
                .addComponent(jTextFieldBuscarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel24)
                .addGap(6, 6, 6)
                .addComponent(jComboBoxBuscarSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel34)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldBuscarNombreSeguro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextFieldBuscarSectorDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel30)
                .addGap(4, 4, 4)
                .addComponent(jTextFieldBuscarEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Apellidos");

        jTextFieldBuscarApellido.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextFieldBuscarApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldBuscarApellidoKeyPressed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Fecha Nacimiento");

        jDateChooseBuscarrFechaNacimiento.setDateFormatString("yyyy-MM-dd");
        jDateChooseBuscarrFechaNacimiento.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jDateChooseBuscarrFechaNacimiento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jDateChooseBuscarrFechaNacimientoKeyPressed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Tipo de sangre");

        jComboBoxBuscarTipoSangre.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jComboBoxBuscarTipoSangre.setToolTipText("");

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("Dirección");

        jTextFieldBuscarAdressDireccion.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextFieldBuscarAdressDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldBuscarAdressDireccionKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanelColumna3Layout = new javax.swing.GroupLayout(jPanelColumna3);
        jPanelColumna3.setLayout(jPanelColumna3Layout);
        jPanelColumna3Layout.setHorizontalGroup(
            jPanelColumna3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jDateChooseBuscarrFechaNacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jComboBoxBuscarTipoSangre, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTextFieldBuscarAdressDireccion)
            .addComponent(jTextFieldBuscarApellido)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelColumna3Layout.setVerticalGroup(
            jPanelColumna3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelColumna3Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(6, 6, 6)
                .addComponent(jTextFieldBuscarApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel26)
                .addGap(6, 6, 6)
                .addComponent(jDateChooseBuscarrFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel25)
                .addGap(10, 10, 10)
                .addComponent(jComboBoxBuscarTipoSangre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel31)
                .addGap(10, 10, 10)
                .addComponent(jTextFieldBuscarAdressDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Buscar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanelColummna1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(2, 2, 2)
                .addComponent(jPanelColumna2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jPanelColumna3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jButton2)))
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanelColumna3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanelColumna2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanelColummna1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Buscar", jPanel1);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel20.setText("No Seguro");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel21.setText("Dirección");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel11.setText("Apelllido");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel22.setText("Teléfono Trabajo");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel12.setText("Teléfono Celular");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel23.setText("Email1");

        jTextFieldTelefonoCelular.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextFieldTelefonoCelular.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldTelefonoCelularFocusLost(evt);
            }
        });

        jTextFieldTelefonoTrabajo.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextFieldTelefonoTrabajo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldTelefonoTrabajoFocusLost(evt);
            }
        });
        jTextFieldTelefonoTrabajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTelefonoTrabajoActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel13.setText("Email2");

        jTextFieldEmail1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextFieldEmail1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldEmail1FocusLost(evt);
            }
        });

        jTextFieldEmail2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextFieldEmail2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldEmail2FocusLost(evt);
            }
        });

        jDateChooserFechaNacimiento.setDateFormatString("yyyy-MM-dd");
        jDateChooserFechaNacimiento.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jDateChooserFechaNacimiento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jDateChooserFechaNacimientoFocusLost(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel14.setText("Teléfono Casa");

        jComboBoxSexo.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jComboBoxSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MASCULINO", "FEMENINO" }));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel15.setText("Tipo de sangre");

        jComboBoxSangre.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jComboBoxSangre.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("Nombre*");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel16.setText("Provincia");

        jTextFieldNombre.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextFieldNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldNombreFocusLost(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton1.setText("Agregar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel17.setText("Sector");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel18.setText("Fecha Nacimiento");

        jTextFieldProvincia.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextFieldProvincia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldProvinciaFocusLost(evt);
            }
        });

        jTextFieldSector.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextFieldSector.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldSectorFocusLost(evt);
            }
        });
        jTextFieldSector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSectorActionPerformed(evt);
            }
        });

        jTextFieldDireccion.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextFieldDireccion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldDireccionFocusLost(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel19.setText("Sexo");

        jTextFieldTelefonoCasa.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextFieldTelefonoCasa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldTelefonoCasaFocusLost(evt);
            }
        });

        jTextFieldNombreSeguro.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextFieldNombreSeguro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldNombreSeguroFocusLost(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel8.setText("Cedula");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("Nombre del Seguro");

        jTextFieldNumeroSeguro.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextFieldNumeroSeguro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldNumeroSeguroFocusLost(evt);
            }
        });
        jTextFieldNumeroSeguro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNumeroSeguroActionPerformed(evt);
            }
        });

        jTextFieldCedula.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextFieldCedula.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldCedulaFocusLost(evt);
            }
        });

        jTextFieldApellido.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextFieldApellido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldApellidoFocusLost(evt);
            }
        });
        jTextFieldApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldApellidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldTelefonoCasa, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldNombreSeguro, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                            .addComponent(jTextFieldNombre, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldEmail2))
                        .addGap(3, 3, 3)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldTelefonoCelular, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldProvincia)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldApellido)
                            .addComponent(jTextFieldNumeroSeguro, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(3, 3, 3)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxSexo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldCedula, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldSector)
                            .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addComponent(jTextFieldTelefonoTrabajo, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldEmail1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBoxSangre, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextFieldDireccion)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jDateChooserFechaNacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addGap(2, 2, 2))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jComboBoxSangre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel15))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(jLabel19)
                            .addComponent(jLabel18)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldNumeroSeguro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jComboBoxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldNombreSeguro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jDateChooserFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldTelefonoCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldTelefonoTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldTelefonoCasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jLabel16)
                            .addComponent(jLabel21)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldSector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldEmail2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Agregar Nuevo", jPanel2);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setText("4000");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jTabbedPane1)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(567, 567, 567))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(1, 1, 1)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
      // this.jtable();
            String fecha_nacimiento = ((javax.swing.JTextField)this.jDateChooserFechaNacimiento.getDateEditor().getUiComponent()).getText();
      //JOptionPane.showMessageDialog(null, fecha_nacimiento);
      String nombre  = this.jTextFieldNombre.getText();
      String  apellido = this.jTextFieldApellido.getText();
      String telefonoCasa = this.jTextFieldTelefonoCasa.getText();
      String telefonoCelular =this.jTextFieldTelefonoCelular.getText();
      String telefonoTrabajo=this.jTextFieldTelefonoTrabajo.getText();
      String email1 =this.jTextFieldEmail1.getText();
      String cedula =this.jTextFieldCedula.getText();

      String email2 =this.jTextFieldEmail2.getText();
      String sexo = this.jComboBoxSexo.getSelectedItem().toString();
      String tipo_sangre = this.user.getIdTipoSangre(this.jComboBoxSangre.getSelectedIndex());
      String provincia = this.jTextFieldProvincia.getText();
      String sector = this.jTextFieldSector.getText();
      String direccion = this.jTextFieldDireccion.getText();
      String nombreSeguro = this.jTextFieldNombreSeguro.getText();
      String numeroSeguro = this.jTextFieldNumeroSeguro.getText();
      
       this.user.setValoresAtributos(nombre, apellido,telefonoCasa,telefonoCelular,telefonoTrabajo,email1,email2,cedula,fecha_nacimiento,sexo,tipo_sangre,provincia,sector,direccion,nombreSeguro,numeroSeguro);                                         

      if(this.user.getAgregar()){
        
      
        //this.user.setValoresAtributos(this.jTextFieldNombre.getText(), this.jTextFieldApellido.getText(),this.jTextFieldTelefonoCasa.getText(),this.jTextFieldTelefonoCelular.getText(),this.jTextFieldTelefonoTrabajo.getText(),this.jTextFieldEmail1.getText(),this.jTextFieldCedula.getText(),this.jTextFieldFechaNacimiento.getText(),this.jComboBoxSexo.getSelectedItem().toString(),tipo_sangre,this.jTextFieldProvincia.getText(),this.jTextFieldSector.getText(),this.jTextFieldDireccion.getText(),this.jTextFieldNombreSeguro.getText(),this.jTextFieldNumeroSeguro.getText());
       //setValoresAtributos(String nombre,String apellido,String telefonoCasa,String telefonoCelular,String telefonoTrabajo,String email1,String email2,String cedula,String fecha_nacimiento,String sexo,String tipo_sangre_id,String provincia,String sector,String direccion,String nombreSeguro,String numeroSeguro); 
       boolean respuesta = this.user.insert();
        if(respuesta){
            this.user.mostrarDatosTabla(this.jTable1, this.jLabel6);
            //this.user.mostrarNuevoDatoTabla(this.jTable1, this.jLabel6);
            this.user.limpiarTexto(this.jTextFieldNombre, this.jTextFieldApellido,this.jTextFieldTelefonoCelular,this.jTextFieldEmail2,this.jTextFieldCedula,this.jTextFieldTelefonoCasa,this.jTextFieldProvincia,this.jTextFieldSector,this.jTextFieldDireccion,this.jComboBoxSexo,this.jComboBoxSangre,this.jTextFieldNombreSeguro,this.jTextFieldNumeroSeguro,this.jDateChooserFechaNacimiento,this.jTextFieldTelefonoTrabajo,this.jTextFieldEmail1);
        }
      }else{
            //JOptionPane.showMessageDialog(null, type_user);
            //String tipo_sangre = this.user.getIdTipoSangre(this.jComboBoxSangre.getSelectedIndex());
            //this.user.setValoresAtributos(this.jTextFieldNombre.getText(), this.jTextFieldApellido.getText(),this.jTextFieldTelefonoCasa.getText(),this.jTextFieldTelefonoCelular.getText(),this.jTextFieldTelefonoTrabajo.getText(),this.jTextFieldEmail1.getText(),this.jTextFieldCedula.getText(),this.jTextFieldFechaNacimiento.getText(),this.jComboBoxSexo.getSelectedItem().toString(),tipo_sangre,this.jTextFieldProvincia.getText(),this.jTextFieldSector.getText(),this.jTextFieldDireccion.getText(),this.jTextFieldNombreSeguro.getText(),this.jTextFieldNumeroSeguro.getText());
             this.user.setValoresAtributos(nombre, apellido,telefonoCasa,telefonoCelular,telefonoTrabajo,email1,email2,cedula,fecha_nacimiento,sexo,tipo_sangre,provincia,sector,direccion,nombreSeguro,numeroSeguro,this.id);
      
            boolean respuesta = this.user.update();
            if(respuesta){
                this.user.mostrarDatosTabla(this.jTable1, this.jLabel6);
                this.user.setAgregar(true);
                this.user.cambiarTestoParaEditar(this.jButton1, this.jLabel9,this.jTextFieldNombre);
                this.user.limpiarTexto(this.jTextFieldNombre, this.jTextFieldApellido,this.jTextFieldTelefonoCelular,this.jTextFieldEmail2,this.jTextFieldCedula,this.jTextFieldTelefonoCasa,this.jTextFieldProvincia,this.jTextFieldSector,this.jTextFieldDireccion,this.jComboBoxSexo,this.jComboBoxSangre,this.jTextFieldNombreSeguro,this.jTextFieldNumeroSeguro,this.jDateChooserFechaNacimiento,this.jTextFieldTelefonoTrabajo,this.jTextFieldEmail1);
            }
          
      }

    }//GEN-LAST:event_jButton1MouseClicked


    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int select = this.jTable1.rowAtPoint(evt.getPoint());
        String id = this.jTable1.getValueAt(select, 0).toString();
        this.id = id;
        System.out.println("Click editar registro "+id);
        String[] respuesta = this.user.mostrarEditarPaciente(id);
        this.user.cambiarTestoParaEditar(this.jButton1,this.jLabel9,this.jTextFieldNombre);
        
        this.jTextFieldNombre.setText(respuesta[1]);
        this.jTextFieldCedula.setText(respuesta[3]);
        //this.jTextField4.setText(respuesta[4]);
        this.jTextFieldApellido.setText(respuesta[2]);
        this.jComboBoxSexo.setSelectedItem(respuesta[5]);
        //this.jTextArea1.setText(respuesta[6]);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTextFieldNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNombreFocusLost
        // TODO add your handling code here:
        //this.user.validarUsuario(this.jTextField1.getText());
    }//GEN-LAST:event_jTextFieldNombreFocusLost

    private void jTextFieldCedulaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCedulaFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCedulaFocusLost

    private void jTextFieldApellidoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldApellidoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldApellidoFocusLost

    private void jTextFieldTelefonoCelularFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldTelefonoCelularFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTelefonoCelularFocusLost

    private void jTextFieldEmail2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldEmail2FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmail2FocusLost

    private void jTextFieldProvinciaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldProvinciaFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldProvinciaFocusLost

    private void jTextFieldApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldApellidoActionPerformed

    private void jTextFieldSectorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldSectorFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSectorFocusLost

    private void jTextFieldSectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSectorActionPerformed

    private void jTextFieldDireccionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldDireccionFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDireccionFocusLost

    private void jTextFieldTelefonoCasaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldTelefonoCasaFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTelefonoCasaFocusLost

    private void jTextFieldNombreSeguroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNombreSeguroFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreSeguroFocusLost

    private void jTextFieldNumeroSeguroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNumeroSeguroFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNumeroSeguroFocusLost

    private void jTextFieldNumeroSeguroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNumeroSeguroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNumeroSeguroActionPerformed

    private void jTextFieldTelefonoTrabajoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldTelefonoTrabajoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTelefonoTrabajoFocusLost

    private void jTextFieldTelefonoTrabajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTelefonoTrabajoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTelefonoTrabajoActionPerformed

    private void jTextFieldEmail1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldEmail1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmail1FocusLost

    private void jDateChooserFechaNacimientoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jDateChooserFechaNacimientoFocusLost
        // TODO add your handling code here:

    }//GEN-LAST:event_jDateChooserFechaNacimientoFocusLost

    private void EliminarPacienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EliminarPacienteMousePressed
        // TODO add your handling code here:
        // TODO add your handling code here:
         // TODO add your handling code here:
        int fila = this.jTable1.getSelectedRow();
         
        String id = this.jTable1.getValueAt(fila, 0).toString();
        String user = this.jTable1.getValueAt(fila, 0).toString();
        
        this.id = id;
        int respuesta = JOptionPane.showConfirmDialog(null, "Desea eliminar este registro?", "Eliminar registro", JOptionPane.YES_NO_OPTION);
        if(respuesta == JOptionPane.YES_OPTION){
            boolean eliminado = this.user.elimnar(id);
            if(eliminado){
                JOptionPane.showMessageDialog(null, "Se elimino correctamente el registro.");
                this.user.mostrarDatosTabla(this.jTable1, this.jLabel6);
                this.user.setAgregar(true);
                this.user.cambiarTestoParaEditar(this.jButton1,this.jLabel9,this.jTextFieldNombre);
                this.user.limpiarTexto(this.jTextFieldNombre, this.jTextFieldApellido,this.jTextFieldTelefonoCelular,this.jTextFieldEmail2,this.jTextFieldCedula,this.jTextFieldTelefonoCasa,this.jTextFieldProvincia,this.jTextFieldSector,this.jTextFieldDireccion,this.jComboBoxSexo,this.jComboBoxSangre,this.jTextFieldNombreSeguro,this.jTextFieldNumeroSeguro,this.jDateChooserFechaNacimiento,this.jTextFieldTelefonoTrabajo,this.jTextFieldEmail1);

            }else{
                 JOptionPane.showMessageDialog(null, "No se pudo eliminar correctamente el registro.");           
            }
        }
        System.out.println("prueba "+id+" prueba ");
    }//GEN-LAST:event_EliminarPacienteMousePressed

    private void EditarEliminarVerEmailMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditarEliminarVerEmailMousePressed
        // TODO add your handling code here:
        int fila = this.jTable1.getSelectedRow();
        String id_patient = this.jTable1.getValueAt(fila, 0).toString();
        new JFrameEmail(mysql,id_patient,this.usuarioID,this.nombreUsuario,this.nombreTituloUsuario).setVisible(true);
    }//GEN-LAST:event_EditarEliminarVerEmailMousePressed

    private void EditarEliminarVerSeguroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditarEliminarVerSeguroMousePressed
        // TODO add your handling code here:
        int fila = this.jTable1.getSelectedRow();
        String id_patient = this.jTable1.getValueAt(fila, 0).toString();
        new JFrameSeguro(mysql,id_patient,this.usuarioID,this.nombreUsuario,this.nombreTituloUsuario).setVisible(true);
                                                     
    }//GEN-LAST:event_EditarEliminarVerSeguroMousePressed

    private void EditarEliminarVerDireccionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditarEliminarVerDireccionMousePressed
        // TODO add your handling code here:
        int fila = this.jTable1.getSelectedRow();
        String id_patient = this.jTable1.getValueAt(fila, 0).toString();
        new JFrameDireccion(mysql,id_patient,this.usuarioID,this.nombreUsuario,this.nombreTituloUsuario).setVisible(true);
    }//GEN-LAST:event_EditarEliminarVerDireccionMousePressed

    private void EditarEliminarVerTelefonoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditarEliminarVerTelefonoMousePressed
        // TODO add your handling code here:
         int fila = this.jTable1.getSelectedRow();
        String id_patient = this.jTable1.getValueAt(fila, 0).toString();
        new JFrameTelefono(mysql,id_patient,this.usuarioID,this.nombreUsuario,this.nombreTituloUsuario).setVisible(true);
        
    }//GEN-LAST:event_EditarEliminarVerTelefonoMousePressed

    private void VerHistoricoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VerHistoricoMousePressed
        // TODO add your handling code here:
        int fila = this.jTable1.getSelectedRow();
        String id_patient = this.jTable1.getValueAt(fila, 0).toString();
        new JFrameHistorialPaciente(mysql,id_patient).setVisible(true);
    }//GEN-LAST:event_VerHistoricoMousePressed

    private void jTextFieldIDPacienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldIDPacienteKeyPressed
        // TODO add your handling code here:
        this.user.buscadorEnter(evt, 1, this.jTextFieldIDPaciente.getText());
    }//GEN-LAST:event_jTextFieldIDPacienteKeyPressed

    private void jTextFieldBuscarNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBuscarNombreKeyPressed
        // TODO add your handling code here:
        this.user.buscadorEnter(evt, 2, this.jTextFieldBuscarNombre.getText());
    }//GEN-LAST:event_jTextFieldBuscarNombreKeyPressed

    private void jTextFieldBuscarApellidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBuscarApellidoKeyPressed
        // TODO add your handling code here:
       this.user.buscadorEnter(evt, 3, this.jTextFieldBuscarApellido.getText());
    }//GEN-LAST:event_jTextFieldBuscarApellidoKeyPressed

    private void jTextFieldBuscarCedulaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBuscarCedulaKeyPressed
        // TODO add your handling code here:
        this.user.buscadorEnter(evt, 4, this.jTextFieldBuscarCedula.getText());

    }//GEN-LAST:event_jTextFieldBuscarCedulaKeyPressed

    private void jDateChooseBuscarrFechaNacimientoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jDateChooseBuscarrFechaNacimientoKeyPressed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "evento press activo");
       String fecha_nacimiento = ((javax.swing.JTextField)this.jDateChooseBuscarrFechaNacimiento.getDateEditor().getUiComponent()).getText();
        this.user.buscadorEnter(evt, 5, fecha_nacimiento);
    }//GEN-LAST:event_jDateChooseBuscarrFechaNacimientoKeyPressed

    private void jTextFieldBuscarNoSeguroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBuscarNoSeguroKeyPressed
        // TODO add your handling code here:
        this.user.buscadorEnter(evt, 8, this.jTextFieldBuscarNoSeguro.getText());
    }//GEN-LAST:event_jTextFieldBuscarNoSeguroKeyPressed

    private void jTextFieldBuscarSectorDireccionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBuscarSectorDireccionKeyPressed
        // TODO add your handling code here:
        this.user.buscadorEnter(evt, 7, this.jTextFieldBuscarSectorDireccion.getText());        
    }//GEN-LAST:event_jTextFieldBuscarSectorDireccionKeyPressed

    private void jTextFieldBuscarTelefonoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBuscarTelefonoKeyPressed
        // TODO add your handling code here:
        this.user.buscadorEnter(evt, 6, this.jTextFieldBuscarTelefono.getText());
    }//GEN-LAST:event_jTextFieldBuscarTelefonoKeyPressed

    private void jTextFieldBuscarDireccionProvinciaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBuscarDireccionProvinciaKeyPressed
        // TODO add your handling code here:
        this.user.buscadorEnter(evt, 9, this.jTextFieldBuscarDireccionProvincia.getText());
    }//GEN-LAST:event_jTextFieldBuscarDireccionProvinciaKeyPressed

    private void jTextFieldBuscarEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBuscarEmailKeyPressed
        // TODO add your handling code here:
        this.user.buscadorEnter(evt, 10, this.jTextFieldBuscarEmail.getText());
    }//GEN-LAST:event_jTextFieldBuscarEmailKeyPressed

    private void jTextFieldBuscarAdressDireccionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBuscarAdressDireccionKeyPressed
        // TODO add your handling code here:
        this.user.buscadorEnter(evt, 11, this.jTextFieldBuscarAdressDireccion.getText());        
    }//GEN-LAST:event_jTextFieldBuscarAdressDireccionKeyPressed

    private void jTextFieldBuscarNombreSeguroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBuscarNombreSeguroKeyPressed
        // TODO add your handling code here:
        this.user.buscadorEnter(evt, 12, this.jTextFieldBuscarNombreSeguro.getText());
    }//GEN-LAST:event_jTextFieldBuscarNombreSeguroKeyPressed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        String sexo = this.jComboBoxBuscarSexo.getSelectedItem().toString().toLowerCase();
        String tipo_sangre = "";
        System.out.println(this.jComboBoxBuscarTipoSangre.getSelectedIndex());
        if(this.jComboBoxBuscarTipoSangre.getSelectedIndex() != 0){
            tipo_sangre = this.user.getIdTipoSangre(this.jComboBoxBuscarTipoSangre.getSelectedIndex()-1);
        }
        String fecha_nacimiento = ((javax.swing.JTextField)this.jDateChooseBuscarrFechaNacimiento.getDateEditor().getUiComponent()).getText();
        this.user.crearBusqueda(this.jTextFieldIDPaciente.getText(),this.jTextFieldBuscarNombre.getText(),this.jTextFieldBuscarApellido.getText(),this.jTextFieldBuscarCedula.getText(),fecha_nacimiento,sexo,this.jTextFieldBuscarEmail.getText(),this.jTextFieldBuscarTelefono.getText(),this.jTextFieldBuscarDireccionProvincia.getText(),this.jTextFieldBuscarSectorDireccion.getText(),this.jTextFieldBuscarAdressDireccion.getText(),this.jTextFieldBuscarNoSeguro.getText(),this.jTextFieldBuscarNombreSeguro.getText(),tipo_sangre);
    }//GEN-LAST:event_jButton2MouseClicked

    
    /**
     * @param args the command line arguments
     */
   //public static void  main(String[] a){
   //   new JFrameBuscarPaciente().setVisible(true);
  // }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem EditarEliminarVerDireccion;
    private javax.swing.JMenuItem EditarEliminarVerEmail;
    private javax.swing.JMenuItem EditarEliminarVerSeguro;
    private javax.swing.JMenuItem EditarEliminarVerTelefono;
    private javax.swing.JMenuItem EliminarPaciente;
    private javax.swing.JMenuItem VerHistorico;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBoxBuscarSexo;
    private javax.swing.JComboBox<String> jComboBoxBuscarTipoSangre;
    private javax.swing.JComboBox<String> jComboBoxSangre;
    private javax.swing.JComboBox<String> jComboBoxSexo;
    private com.toedter.calendar.JDateChooser jDateChooseBuscarrFechaNacimiento;
    private com.toedter.calendar.JDateChooser jDateChooserFechaNacimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelColummna1;
    private javax.swing.JPanel jPanelColumna2;
    private javax.swing.JPanel jPanelColumna3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldApellido;
    private javax.swing.JTextField jTextFieldBuscarAdressDireccion;
    private javax.swing.JTextField jTextFieldBuscarApellido;
    private javax.swing.JTextField jTextFieldBuscarCedula;
    private javax.swing.JTextField jTextFieldBuscarDireccionProvincia;
    private javax.swing.JTextField jTextFieldBuscarEmail;
    private javax.swing.JTextField jTextFieldBuscarNoSeguro;
    private javax.swing.JTextField jTextFieldBuscarNombre;
    private javax.swing.JTextField jTextFieldBuscarNombreSeguro;
    private javax.swing.JTextField jTextFieldBuscarSectorDireccion;
    private javax.swing.JTextField jTextFieldBuscarTelefono;
    private javax.swing.JTextField jTextFieldCedula;
    private javax.swing.JTextField jTextFieldDireccion;
    private javax.swing.JTextField jTextFieldEmail1;
    private javax.swing.JTextField jTextFieldEmail2;
    private javax.swing.JTextField jTextFieldIDPaciente;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldNombreSeguro;
    private javax.swing.JTextField jTextFieldNumeroSeguro;
    private javax.swing.JTextField jTextFieldProvincia;
    private javax.swing.JTextField jTextFieldSector;
    private javax.swing.JTextField jTextFieldTelefonoCasa;
    private javax.swing.JTextField jTextFieldTelefonoCelular;
    private javax.swing.JTextField jTextFieldTelefonoTrabajo;
    // End of variables declaration//GEN-END:variables

}
