/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app.jframes;
import app.Classes.ClassCrearPaciente;
/**
 *
 * @author Eudy
 */
import conection.Mysql;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class JFrameCrearPaciente extends javax.swing.JFrame {

    
    private int lineas = 10;
    private String palabraBuscar="",id="";
    private conection.Mysql mysql;
    private ClassCrearPaciente user ;
    /**
     * Creates new form User
     */
    public JFrameCrearPaciente() {
        initComponents();
       this.user.mostrarDatosTabla(jTable1,this.jLabel6);
      // this.jtable();
    }
    public JFrameCrearPaciente(conection.Mysql mysql) {
       initComponents();
        this.mysql = mysql;
        user = new ClassCrearPaciente(this.mysql); 
        this.user.llenarComboBox(this.jComboBoxSangre);
        this.user.mostrarDatosTabla(jTable1,this.jLabel6);
       
      // this.jtable();
    }
    
    /*EJEMPLO SIMPLE PARA MOSTRAR DATOS EN UNA TABLA
    public void jtable(){
            JOptionPane.showMessageDialog(null, "Tabla");
           //DefaultTableModel modelo = (DefaultTableModel) this.jTable1.getModel();
           
           String[] titulos = {"id","usuario"};
           this.lineas = this.lineas + 2;
          //modelo.setColumnIdentifiers(titulos);
           
           Object[][] fila = new Object[this.lineas][2];
           for(int c = 0 ; c < this.lineas ; c++){
               System.out.println("---- x "+ c);
                //for(int i = 0 ; i < 2 ; i++){
                    fila[c][0] = "x "+ c+" y ";
                    //System.out.println("x "+ c+" y "+i);
                    fila[c][1]  = "Eudy";
                    //modelo.addRow(fila);
                //}
           }
          DefaultTableModel modelo = new DefaultTableModel(fila,titulos);
          this.jTable1.setModel(modelo);
    }*/
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        VerHistorico = new javax.swing.JMenuItem();
        EditarEliminarVerPaciente = new javax.swing.JMenuItem();
        EditarEliminarVerTelefono = new javax.swing.JMenuItem();
        EditarEliminarVerEmail = new javax.swing.JMenuItem();
        EditarEliminarVerDireccion = new javax.swing.JMenuItem();
        EditarEliminarVerSeguro = new javax.swing.JMenuItem();
        EliminarPaciente = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldCedula = new javax.swing.JTextField();
        jTextFieldApellido = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldTelefonoCelular = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldEmail2 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jComboBoxSexo = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jComboBoxSangre = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextFieldProvincia = new javax.swing.JTextField();
        jTextFieldSector = new javax.swing.JTextField();
        jTextFieldDireccion = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextFieldTelefonoCasa = new javax.swing.JTextField();
        jTextFieldNombreSeguro = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNumeroSeguro = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jTextFieldTelefonoTrabajo = new javax.swing.JTextField();
        jTextFieldEmail1 = new javax.swing.JTextField();
        jDateChooserFechaNacimiento = new com.toedter.calendar.JDateChooser();

        VerHistorico.setText("VerHistorico");
        jPopupMenu1.add(VerHistorico);

        EditarEliminarVerPaciente.setText("Editar / Eliminar / Ver Paciente");
        EditarEliminarVerPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                EditarEliminarVerPacienteMousePressed(evt);
            }
        });
        jPopupMenu1.add(EditarEliminarVerPaciente);

        EditarEliminarVerTelefono.setText("Editar / Eliminar / Ver Teléfono");
        jPopupMenu1.add(EditarEliminarVerTelefono);

        EditarEliminarVerEmail.setText("Editar / Eliminar / Ver Email");
        EditarEliminarVerEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                EditarEliminarVerEmailMousePressed(evt);
            }
        });
        jPopupMenu1.add(EditarEliminarVerEmail);

        EditarEliminarVerDireccion.setText("Editar / Eliminar / Ver Dirección");
        EditarEliminarVerDireccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                EditarEliminarVerDireccionMousePressed(evt);
            }
        });
        jPopupMenu1.add(EditarEliminarVerDireccion);

        EditarEliminarVerSeguro.setText("Editar / Eliminar / Ver Seguro");
        EditarEliminarVerSeguro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                EditarEliminarVerSeguroMousePressed(evt);
            }
        });
        jPopupMenu1.add(EditarEliminarVerSeguro);

        EliminarPaciente.setText("EliminarPaciente");
        EliminarPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                EliminarPacienteMousePressed(evt);
            }
        });
        jPopupMenu1.add(EliminarPaciente);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Administrar Paciente");
        setPreferredSize(new java.awt.Dimension(774, 500));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Administrar Paciente");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("Nombre*");

        jTextFieldNombre.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextFieldNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldNombreFocusLost(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton1.setText("Agregar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Nombre de usuario"
            }
        ));
        jTable1.setComponentPopupMenu(jPopupMenu1);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField2KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField2KeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setText("Total de hospital");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setText("4000");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel7.setText("Buscar hospital");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel8.setText("Cedula");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Agregar Paciente");

        jTextFieldCedula.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextFieldCedula.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldCedulaFocusLost(evt);
            }
        });

        jTextFieldApellido.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextFieldApellido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldApellidoFocusLost(evt);
            }
        });
        jTextFieldApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldApellidoActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel11.setText("Apelllido");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel12.setText("Teléfono Celular");

        jTextFieldTelefonoCelular.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextFieldTelefonoCelular.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldTelefonoCelularFocusLost(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel13.setText("Email2");

        jTextFieldEmail2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextFieldEmail2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldEmail2FocusLost(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel14.setText("Teléfono Casa");

        jComboBoxSexo.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jComboBoxSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MASCULINO", "FEMENINO" }));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel15.setText("Tipo de sangre");

        jComboBoxSangre.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jComboBoxSangre.setToolTipText("");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel16.setText("Provincia");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel17.setText("Sector");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel18.setText("Fecha Nacimiento");

        jTextFieldProvincia.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextFieldProvincia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldProvinciaFocusLost(evt);
            }
        });

        jTextFieldSector.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextFieldSector.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldSectorFocusLost(evt);
            }
        });
        jTextFieldSector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSectorActionPerformed(evt);
            }
        });

        jTextFieldDireccion.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextFieldDireccion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldDireccionFocusLost(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel19.setText("Sexo");

        jTextFieldTelefonoCasa.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextFieldTelefonoCasa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldTelefonoCasaFocusLost(evt);
            }
        });

        jTextFieldNombreSeguro.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextFieldNombreSeguro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldNombreSeguroFocusLost(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("Nombre del Seguro");

        jTextFieldNumeroSeguro.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextFieldNumeroSeguro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldNumeroSeguroFocusLost(evt);
            }
        });
        jTextFieldNumeroSeguro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNumeroSeguroActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel20.setText("No Seguro");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel21.setText("Dirección");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel22.setText("Teléfono Trabajo");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel23.setText("Email1");

        jTextFieldTelefonoTrabajo.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextFieldTelefonoTrabajo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldTelefonoTrabajoFocusLost(evt);
            }
        });
        jTextFieldTelefonoTrabajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTelefonoTrabajoActionPerformed(evt);
            }
        });

        jTextFieldEmail1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextFieldEmail1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldEmail1FocusLost(evt);
            }
        });

        jDateChooserFechaNacimiento.setDateFormatString("yyyy-MM-dd");
        jDateChooserFechaNacimiento.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jDateChooserFechaNacimiento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jDateChooserFechaNacimientoFocusLost(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldEmail2)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldNombre, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldTelefonoCasa, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldNombreSeguro, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldTelefonoCelular, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldProvincia)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldApellido)
                            .addComponent(jTextFieldNumeroSeguro, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxSexo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldCedula, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldSector)
                            .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldTelefonoTrabajo, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldEmail1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBoxSangre, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextFieldDireccion)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jDateChooserFechaNacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(601, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                                .addGap(564, 564, 564))
                            .addComponent(jTextField2)))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBoxSangre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel2)
                            .addComponent(jLabel11)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel20)
                    .addComponent(jLabel19)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldNombreSeguro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldNumeroSeguro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBoxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jDateChooserFechaNacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel12)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTelefonoCasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldTelefonoCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldTelefonoTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel13)
                    .addComponent(jLabel16)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldEmail2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField2))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
      // this.jtable();
            String fecha_nacimiento = ((javax.swing.JTextField)this.jDateChooserFechaNacimiento.getDateEditor().getUiComponent()).getText();
      //JOptionPane.showMessageDialog(null, fecha_nacimiento);
      String nombre  = this.jTextFieldNombre.getText();
      String  apellido = this.jTextFieldApellido.getText();
      String telefonoCasa = this.jTextFieldTelefonoCasa.getText();
      String telefonoCelular =this.jTextFieldTelefonoCelular.getText();
      String telefonoTrabajo=this.jTextFieldTelefonoTrabajo.getText();
      String email1 =this.jTextFieldEmail1.getText();
      String cedula =this.jTextFieldCedula.getText();

      String email2 =this.jTextFieldEmail2.getText();
      String sexo = this.jComboBoxSexo.getSelectedItem().toString();
      String tipo_sangre = this.user.getIdTipoSangre(this.jComboBoxSangre.getSelectedIndex());
      String provincia = this.jTextFieldProvincia.getText();
      String sector = this.jTextFieldSector.getText();
      String direccion = this.jTextFieldDireccion.getText();
      String nombreSeguro = this.jTextFieldNombreSeguro.getText();
      String numeroSeguro = this.jTextFieldNumeroSeguro.getText();
      
       this.user.setValoresAtributos(nombre, apellido,telefonoCasa,telefonoCelular,telefonoTrabajo,email1,email2,cedula,fecha_nacimiento,sexo,tipo_sangre,provincia,sector,direccion,nombreSeguro,numeroSeguro);                                         

      if(this.user.getAgregar()){
        
      
        //this.user.setValoresAtributos(this.jTextFieldNombre.getText(), this.jTextFieldApellido.getText(),this.jTextFieldTelefonoCasa.getText(),this.jTextFieldTelefonoCelular.getText(),this.jTextFieldTelefonoTrabajo.getText(),this.jTextFieldEmail1.getText(),this.jTextFieldCedula.getText(),this.jTextFieldFechaNacimiento.getText(),this.jComboBoxSexo.getSelectedItem().toString(),tipo_sangre,this.jTextFieldProvincia.getText(),this.jTextFieldSector.getText(),this.jTextFieldDireccion.getText(),this.jTextFieldNombreSeguro.getText(),this.jTextFieldNumeroSeguro.getText());
       //setValoresAtributos(String nombre,String apellido,String telefonoCasa,String telefonoCelular,String telefonoTrabajo,String email1,String email2,String cedula,String fecha_nacimiento,String sexo,String tipo_sangre_id,String provincia,String sector,String direccion,String nombreSeguro,String numeroSeguro); 
       boolean respuesta = this.user.insert();
        if(respuesta){
            this.user.mostrarDatosTabla(this.jTable1, this.jLabel6);
            //this.user.mostrarNuevoDatoTabla(this.jTable1, this.jLabel6);
            this.user.limpiarTexto(this.jTextFieldNombre, this.jTextFieldApellido,this.jTextFieldTelefonoCelular,this.jTextFieldEmail2,this.jTextFieldCedula,this.jTextFieldTelefonoCasa,this.jTextFieldProvincia,this.jTextFieldSector,this.jTextFieldDireccion,this.jComboBoxSexo,this.jComboBoxSangre,this.jTextFieldNombreSeguro,this.jTextFieldNumeroSeguro,this.jDateChooserFechaNacimiento,this.jTextFieldTelefonoTrabajo,this.jTextFieldEmail1);
        }
      }else{
            //JOptionPane.showMessageDialog(null, type_user);
            //String tipo_sangre = this.user.getIdTipoSangre(this.jComboBoxSangre.getSelectedIndex());
            //this.user.setValoresAtributos(this.jTextFieldNombre.getText(), this.jTextFieldApellido.getText(),this.jTextFieldTelefonoCasa.getText(),this.jTextFieldTelefonoCelular.getText(),this.jTextFieldTelefonoTrabajo.getText(),this.jTextFieldEmail1.getText(),this.jTextFieldCedula.getText(),this.jTextFieldFechaNacimiento.getText(),this.jComboBoxSexo.getSelectedItem().toString(),tipo_sangre,this.jTextFieldProvincia.getText(),this.jTextFieldSector.getText(),this.jTextFieldDireccion.getText(),this.jTextFieldNombreSeguro.getText(),this.jTextFieldNumeroSeguro.getText());
             this.user.setValoresAtributos(nombre, apellido,telefonoCasa,telefonoCelular,telefonoTrabajo,email1,email2,cedula,fecha_nacimiento,sexo,tipo_sangre,provincia,sector,direccion,nombreSeguro,numeroSeguro,this.id);
      
            boolean respuesta = this.user.update();
            if(respuesta){
                this.user.mostrarDatosTabla(this.jTable1, this.jLabel6);
                this.user.setAgregar(true);
                this.user.cambiarTestoParaEditar(this.jButton1, this.jLabel9,this.jTextFieldNombre);
                this.user.limpiarTexto(this.jTextFieldNombre, this.jTextFieldApellido,this.jTextFieldTelefonoCelular,this.jTextFieldEmail2,this.jTextFieldCedula,this.jTextFieldTelefonoCasa,this.jTextFieldProvincia,this.jTextFieldSector,this.jTextFieldDireccion,this.jComboBoxSexo,this.jComboBoxSangre,this.jTextFieldNombreSeguro,this.jTextFieldNumeroSeguro,this.jDateChooserFechaNacimiento,this.jTextFieldTelefonoTrabajo,this.jTextFieldEmail1);
            }
          
      }

    }//GEN-LAST:event_jButton1MouseClicked

    private void jTextField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField2KeyTyped


    private void jTextField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyReleased
        // TODO add your handling code here:
        this.palabraBuscar = this.jTextField2.getText();
        //        this.palabraBuscar +=evt.getKeyChar();

       // System.out.println(this.palabraBuscar);
       // this.user.mostrarDatosTabla(this.jTable1, this.jLabel6,this.palabraBuscar);
    }//GEN-LAST:event_jTextField2KeyReleased

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int select = this.jTable1.rowAtPoint(evt.getPoint());
        String id = this.jTable1.getValueAt(select, 0).toString();
        this.id = id;
        System.out.println("Click editar registro "+id);
        String[] respuesta = this.user.mostrarEditarPaciente(id);
        this.user.cambiarTestoParaEditar(this.jButton1,this.jLabel9,this.jTextFieldNombre);
        
        this.jTextFieldNombre.setText(respuesta[1]);
        this.jTextFieldCedula.setText(respuesta[3]);
        //this.jTextField4.setText(respuesta[4]);
        this.jTextFieldApellido.setText(respuesta[2]);
        this.jComboBoxSexo.setSelectedItem(respuesta[5]);
        //this.jTextArea1.setText(respuesta[6]);
    }//GEN-LAST:event_jTable1MouseClicked

    private void EditarEliminarVerPacienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditarEliminarVerPacienteMousePressed
        // TODO add your handling code here:
         // TODO add your handling code here:
       /* int fila = this.jTable1.getSelectedRow();
         
        String id = this.jTable1.getValueAt(fila, 0).toString();
        String user = this.jTable1.getValueAt(fila, 0).toString();
        
        this.id = id;
        int respuesta = JOptionPane.showConfirmDialog(null, "Desea eliminar este registro?", "Eliminar registro", JOptionPane.YES_NO_OPTION);
        if(respuesta == JOptionPane.YES_OPTION){
            boolean eliminado = this.user.elimnar(id);
            if(eliminado){
                JOptionPane.showMessageDialog(null, "Se elimino correctamente el registro.");
                this.user.mostrarDatosTabla(this.jTable1, this.jLabel6);
                 this.user.setAgregar(true);
                this.user.cambiarTestoParaEditar(this.jButton1, this.jLabel9,this.jTextField1);
//                this.user.limpiarTexto( this.jTextField1, this.jTextField3, this.jTextField4, this.jTextField5, this.jTextField6, this.jTextArea1);

            }else{
                 JOptionPane.showMessageDialog(null, "No se pudo eliminar correctamente el registro.");           
            }
        }/*else{
            //JOptionPane.showMessageDialog(null, "NO");

        }*******
       //String id1 = this.jTable1.getModel().getValueAt(this.jTable1.getSelectedRow(),0).toString();
        //String id1 = this.jTable1.getValueAt(select, 0).toString();
        
        
        
        System.out.println("prueba "+id+" prueba ");*****/
    }//GEN-LAST:event_EditarEliminarVerPacienteMousePressed

    private void jTextFieldNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNombreFocusLost
        // TODO add your handling code here:
        //this.user.validarUsuario(this.jTextField1.getText());
    }//GEN-LAST:event_jTextFieldNombreFocusLost

    private void jTextFieldCedulaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCedulaFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCedulaFocusLost

    private void jTextFieldApellidoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldApellidoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldApellidoFocusLost

    private void jTextFieldTelefonoCelularFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldTelefonoCelularFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTelefonoCelularFocusLost

    private void jTextFieldEmail2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldEmail2FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmail2FocusLost

    private void jTextFieldProvinciaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldProvinciaFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldProvinciaFocusLost

    private void jTextFieldApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldApellidoActionPerformed

    private void jTextFieldSectorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldSectorFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSectorFocusLost

    private void jTextFieldSectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSectorActionPerformed

    private void jTextFieldDireccionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldDireccionFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDireccionFocusLost

    private void jTextFieldTelefonoCasaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldTelefonoCasaFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTelefonoCasaFocusLost

    private void jTextFieldNombreSeguroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNombreSeguroFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreSeguroFocusLost

    private void jTextFieldNumeroSeguroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNumeroSeguroFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNumeroSeguroFocusLost

    private void jTextFieldNumeroSeguroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNumeroSeguroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNumeroSeguroActionPerformed

    private void jTextFieldTelefonoTrabajoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldTelefonoTrabajoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTelefonoTrabajoFocusLost

    private void jTextFieldTelefonoTrabajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTelefonoTrabajoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTelefonoTrabajoActionPerformed

    private void jTextFieldEmail1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldEmail1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmail1FocusLost

    private void jDateChooserFechaNacimientoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jDateChooserFechaNacimientoFocusLost
        // TODO add your handling code here:

    }//GEN-LAST:event_jDateChooserFechaNacimientoFocusLost

    private void EliminarPacienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EliminarPacienteMousePressed
        // TODO add your handling code here:
        // TODO add your handling code here:
         // TODO add your handling code here:
        int fila = this.jTable1.getSelectedRow();
         
        String id = this.jTable1.getValueAt(fila, 0).toString();
        String user = this.jTable1.getValueAt(fila, 0).toString();
        
        this.id = id;
        int respuesta = JOptionPane.showConfirmDialog(null, "Desea eliminar este registro?", "Eliminar registro", JOptionPane.YES_NO_OPTION);
        if(respuesta == JOptionPane.YES_OPTION){
            boolean eliminado = this.user.elimnar(id);
            if(eliminado){
                JOptionPane.showMessageDialog(null, "Se elimino correctamente el registro.");
                this.user.mostrarDatosTabla(this.jTable1, this.jLabel6);
                this.user.setAgregar(true);
                this.user.cambiarTestoParaEditar(this.jButton1,this.jLabel9,this.jTextFieldNombre);
                this.user.limpiarTexto(this.jTextFieldNombre, this.jTextFieldApellido,this.jTextFieldTelefonoCelular,this.jTextFieldEmail2,this.jTextFieldCedula,this.jTextFieldTelefonoCasa,this.jTextFieldProvincia,this.jTextFieldSector,this.jTextFieldDireccion,this.jComboBoxSexo,this.jComboBoxSangre,this.jTextFieldNombreSeguro,this.jTextFieldNumeroSeguro,this.jDateChooserFechaNacimiento,this.jTextFieldTelefonoTrabajo,this.jTextFieldEmail1);

            }else{
                 JOptionPane.showMessageDialog(null, "No se pudo eliminar correctamente el registro.");           
            }
        }
        System.out.println("prueba "+id+" prueba ");
    }//GEN-LAST:event_EliminarPacienteMousePressed

    private void EditarEliminarVerEmailMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditarEliminarVerEmailMousePressed
        // TODO add your handling code here:
        int fila = this.jTable1.getSelectedRow();
        String id_patient = this.jTable1.getValueAt(fila, 0).toString();
        new JFrameEmail(mysql,id_patient).setVisible(true);
    }//GEN-LAST:event_EditarEliminarVerEmailMousePressed

    private void EditarEliminarVerSeguroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditarEliminarVerSeguroMousePressed
        // TODO add your handling code here:
        int fila = this.jTable1.getSelectedRow();
        String id_patient = this.jTable1.getValueAt(fila, 0).toString();
        new JFrameSeguro(mysql,id_patient).setVisible(true);
                                                     
    }//GEN-LAST:event_EditarEliminarVerSeguroMousePressed

    private void EditarEliminarVerDireccionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditarEliminarVerDireccionMousePressed
        // TODO add your handling code here:
        int fila = this.jTable1.getSelectedRow();
        String id_patient = this.jTable1.getValueAt(fila, 0).toString();
        new JFrameDireccion(mysql,id_patient).setVisible(true);
    }//GEN-LAST:event_EditarEliminarVerDireccionMousePressed

    
    /**
     * @param args the command line arguments
     */
   //public static void  main(String[] a){
   //   new JFrameCrearPaciente().setVisible(true);
  // }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem EditarEliminarVerDireccion;
    private javax.swing.JMenuItem EditarEliminarVerEmail;
    private javax.swing.JMenuItem EditarEliminarVerPaciente;
    private javax.swing.JMenuItem EditarEliminarVerSeguro;
    private javax.swing.JMenuItem EditarEliminarVerTelefono;
    private javax.swing.JMenuItem EliminarPaciente;
    private javax.swing.JMenuItem VerHistorico;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBoxSangre;
    private javax.swing.JComboBox<String> jComboBoxSexo;
    private com.toedter.calendar.JDateChooser jDateChooserFechaNacimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextFieldApellido;
    private javax.swing.JTextField jTextFieldCedula;
    private javax.swing.JTextField jTextFieldDireccion;
    private javax.swing.JTextField jTextFieldEmail1;
    private javax.swing.JTextField jTextFieldEmail2;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldNombreSeguro;
    private javax.swing.JTextField jTextFieldNumeroSeguro;
    private javax.swing.JTextField jTextFieldProvincia;
    private javax.swing.JTextField jTextFieldSector;
    private javax.swing.JTextField jTextFieldTelefonoCasa;
    private javax.swing.JTextField jTextFieldTelefonoCelular;
    private javax.swing.JTextField jTextFieldTelefonoTrabajo;
    // End of variables declaration//GEN-END:variables

}
